## Some Testing with yt-dlp

In [ ]:
!pip install yt-dlp

Collecting yt-dlp
  Downloading yt_dlp-2024.7.25-py3-none-any.whl.metadata (170 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.1/170.1 kB 8.5 MB/s eta 0:00:00
Collecting brotli (from yt-dlp)
  Downloading Brotli-1.1.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (5.5 kB)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from yt-dlp) (2024.7.4)
Collecting mutagen (from yt-dlp)
  Downloading mutagen-1.47.0-py3-none-any.whl.metadata (1.7 kB)
Collecting pycryptodomex (from yt-dlp)
  Downloading pycryptodomex-3.20.0-cp35-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
Collecting requests<3,>=2.32.2 (from yt-dlp)
  Downloading requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: urllib3<3,>=1.26.17 in /usr/local/lib/python3.10/dist-packages (from yt-dlp) (2.0.7)
Collecting websockets>=12.0 (from yt-dlp)
  Downloading websockets-12.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.32.2->yt-dlp) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.32.2->yt-dlp) (3.7)
Downloading yt_dlp-2024.7.25-py3-none-any.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 52.0 MB/s eta 0:00:00
Downloading requests-2.32.3-py3-none-any.whl (64 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.9/64.9 kB 6.5 MB/s eta 0:00:00
Downloading websockets-12.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (130 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.2/130.2 kB 13.6 MB/s eta 0:00:00
Downloading Brotli-1.1.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (3.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 85.0 MB/s eta 0:00:00
Downloading mutagen-1.47.0-py3-none-any.whl (194 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.4/194.4 kB 16.3 MB/s eta 0:00:00
Downloading pycryptodomex-3.20.0-cp35-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 68.2 MB/s eta 0:00:00
Installing collected packages: brotli, websockets, requests, pycryptodomex, mutagen, yt-dlp
  Attempting uninstall: requests
    Found existing installation: requests 2.31.0
    Uninstalling requests-2.31.0:
      Successfully uninstalled requests-2.31.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests==2.31.0, but you have requests 2.32.3 which is incompatible.
Successfully installed brotli-1.1.0 mutagen-1.47.0 pycryptodomex-3.20.0 requests-2.32.3 websockets-12.0 yt-dlp-2024.7.25

### Information about `yt-dlp`

```
ydl_opts = {
    'format': 'bestaudio/best',
    'extractaudio': True,
    'audioformat': 'mp3',
    'outtmpl': '/content/drive/MyDrive/%(title)s.%(ext)s',
    'postprocessors': [{
        'key': 'FFmpegExtractAudio',
        'preferredcodec': 'mp3',
        'preferredquality': '192',
    }],
    'noplaylist': True,
    'quiet': False,
    'retries': 5,
    'cookies': '/path/to/cookies.txt',
    'writeinfojson': True,
    'write_subtitles': True,
    'subtitleslangs': ['en'],
}
```

## Testing with a url

In [ ]:
import yt_dlp

url='https://youtu.be/Sjt5R6wlEIk?si=7GQT-276yv2VlWsu'

ydl_opts = {
    'format': 'bestaudio/best',
    'postprocessors': [{
        'key': 'FFmpegExtractAudio',
        'preferredcodec': 'wav',
        'preferredquality': '192',
    }],
    'outtmpl': '1.%(ext)s',
}

with yt_dlp.YoutubeDL(ydl_opts) as ydl:
    ydl.download([url])

[youtube] Extracting URL: https://youtu.be/Sjt5R6wlEIk?si=7GQT-276yv2VlWsu
[youtube] Sjt5R6wlEIk: Downloading webpage
[youtube] Sjt5R6wlEIk: Downloading ios player API JSON
[youtube] Sjt5R6wlEIk: Downloading player 1f8742dc
[youtube] Sjt5R6wlEIk: Downloading m3u8 information
[info] Sjt5R6wlEIk: Downloading 1 format(s): 251
[download] Destination: 1.webm
[download] 100% of    5.40MiB in 00:00:01 at 3.76MiB/s
[ExtractAudio] Destination: 1.wav
Deleting original file 1.webm (pass -k to keep)

In [ ]:
!pip install openai-whisper

Collecting openai-whisper
  Downloading openai-whisper-20231117.tar.gz (798 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 798.6/798.6 kB 37.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: triton<3,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from openai-whisper) (2.3.1)
Requirement already satisfied: numba in /usr/local/lib/python3.10/dist-packages (from openai-whisper) (0.60.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from openai-whisper) (1.25.2)
Requirement already satisfied: torch in /usr/local/lib/python3.10/dist-packages (from openai-whisper) (2.3.1+cu121)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from openai-whisper) (4.66.4)
Requirement already satisfied: more-itertools in /usr/local/lib/python3.10/dist-packages (from openai-whisper) (10.3.0)
Collecting tiktoken (from openai-whisper)
  Downloading tiktoken-0.7.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from triton<3,>=2.0.0->openai-whisper) (3.15.4)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.10/dist-packages (from numba->openai-whisper) (0.43.0)
Requirement already satisfied: regex>=2022.1.18 in /usr/local/lib/python3.10/dist-packages (from tiktoken->openai-whisper) (2024.5.15)
Requirement already satisfied: requests>=2.26.0 in /usr/local/lib/python3.10/dist-packages (from tiktoken->openai-whisper) (2.32.3)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.10/dist-packages (from torch->openai-whisper) (4.12.2)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch->openai-whisper) (1.13.1)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch->openai-whisper) (3.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch->openai-whisper) (3.1.4)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch->openai-whisper) (2024.6.1)
Collecting nvidia-cuda-nvrtc-cu12==12.1.105 (from torch->openai-whisper)
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.1.105 (from torch->openai-whisper)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.1.105 (from torch->openai-whisper)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==8.9.2.26 (from torch->openai-whisper)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.1.3.1 (from torch->openai-whisper)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.0.2.54 (from torch->openai-whisper)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.2.106 (from torch->openai-whisper)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.4.5.107 (from torch->openai-whisper)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.1.0.106 (from torch->openai-whisper)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-nccl-cu12==2.20.5 (from torch->openai-whisper)
  Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvtx-cu12==12.1.105 (from torch->openai-whisper)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-nvjitlink-cu12 (from nvidia-cusolver-cu12==11.4.5.107->torch->openai-whisper)
  Downloading nvidia_nvjitlink_cu12-12.5.82-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.26.0->tiktoken->openai-whisper) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.26.0->tiktoken->openai-whisper) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.26.0->tiktoken->openai-whisper) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.26.0->tiktoken->openai-whisper) (2024.7.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch->openai-whisper) (2.1.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy->torch->openai-whisper) (1.3.0)
Downloading tiktoken-0.7.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 46.4 MB/s eta 0:00:00
Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl (176.2 MB)
Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
Downloading nvidia_nvjitlink_cu12-12.5.82-py3-none-manylinux2014_x86_64.whl (21.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.3/21.3 MB 13.8 MB/s eta 0:00:00
Building wheels for collected packages: openai-whisper
  Building wheel for openai-whisper (pyproject.toml) ... done
  Created wheel for openai-whisper: filename=openai_whisper-20231117-py3-none-any.whl size=801360 sha256=a58da9fe07813f9db8e9c477dafafa7d8d2c6e619ce95a194df148ab45bea650
  Stored in directory: /root/.cache/pip/wheels/d0/85/e1/9361b4cbea7dd4b7f6702fa4c3afc94877952eeb2b62f45f56
Successfully built openai-whisper
Installing collected packages: nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, tiktoken, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, openai-whisper
Successfully installed nvidia-cublas-cu12-12.1.3.1 nvidia-cuda-cupti-cu12-12.1.105 nvidia-cuda-nvrtc-cu12-12.1.105 nvidia-cuda-runtime-cu12-12.1.105 nvidia-cudnn-cu12-8.9.2.26 nvidia-cufft-cu12-11.0.2.54 nvidia-curand-cu12-10.3.2.106 nvidia-cusolver-cu12-11.4.5.107 nvidia-cusparse-cu12-12.1.0.106 nvidia-nccl-cu12-2.20.5 nvidia-nvjitlink-cu12-12.5.82 nvidia-nvtx-cu12-12.1.105 openai-whisper-20231117 tiktoken-0.7.0

In [ ]:
import whisper

model= whisper.load_model('base')

100%|███████████████████████████████████████| 139M/139M [00:01<00:00, 79.1MiB/s]

In [ ]:
result= model.transcribe('/content/1.wav')

print(result['text'])

 I'm on YouTube a lot. For work, for fun, and for learning. It truly is a one-of-a-kind platform that has tons to offer. I gladly pay for a YouTube premium even, not an ad, just trying to emphasize how much I use YouTube. But there are many things wrong with the site, especially when it comes to language learning. Which led me to discover one of my favorite tools that I use all the time and will probably continue to use for a very long time. It's called YT-DLP. Ooh, a very fancy name. I want to show it to you today and try to demystify it a bit since it's fairly technical or at least looks fairly technical. In the recent, it has that reputation is because it's a command line tool. So it looks like something out of a spy movie to a lot of people. But it's actually pretty easy to use. And the reason it uses the command line is because it doesn't need all of the other bells and whistles of a traditional program. Because all it does is download YouTube videos like this one if you wanted. It's really simple. If I want to download a video, I just type YT-DLP and then paste the video URL and it does it. There are more features that we'll cover in a second like grabbing just the audio or a video with subtitles or even a whole playlist. But that's the basics of it. However, if you're not really comfortable with techy things, it might be best to skip this tool and just use a generic YouTube downloader website of which there are many. As that said, let's look at how to install the program. First, you'll need Python and PIP to run and install the program. They're pretty easy to install for all systems. I've linked some articles for each operating to some down in the description. It's mostly following some steps and copying pasting commands. So you should be all right. Once you have PIP, you can run this command. Which will install the program. If that doesn't work, try changing Python 3 at the beginning to just PIE or Python. Every system needs something a little different. If PIP isn't working, check out the documentation where there's a bunch of different ways that you can install the program. Now that the tool's installed, you'll be able to run the command YGDRP and put in some parameters to tell the program how to download a video. Obviously, you'll need to tell it which video to download, but you can also add other information. Here are the commands I use most often so that you can just copy them. First is the basic, just download this video command. YGDRP, video URL, and it will just download it all. Then you can watch and rewatch it with whatever video player you prefer. I'd like to use MVV player. If a video has subtitles, you can download the video and it subtitles with this command. The laying part should be replaced with the two letter language code. So for a checked video that I might download, I would put in CS. A similar command is adding yes playlist and looking a whole playlist instead of just a single video. Which will download all of the videos on that playlist and all the subtitles. Just remember to replace the line with the code and that sort of thing. And the same thing would work with a playlist without subtitles. You can just remove all the information about the subs, so that part that says subtitles and the language thing, and it will download all of the videos. This can be great if you make your own playlists, maybe when you're watching on your phone, and then want to download those videos and bulk later without doing each one at a time. The Refold YouTube channel also has a bunch of curated playlists for many different languages and many different topics, so I recommend you go over to our channel and check those out. The final command I use is just to download the audio of a video on its own, so that I can use it for listening or chorusing later. That command is here. Just replace the URL with whatever you want to download and you'll have it as an MP3 file. Those are all the commands that I think are useful. I always copy and paste these commands since I forget them every single time. Also in the description, there's a page you can go to that has all of them easily accessible and any future ones that I decided to put in there, so that you can bookmark the page or download it or whatever. Refold.link slash yt-dlp-commands. And the program has a ton more to offer. If you're interested, definitely check out the documentation and see what else you can do. But before I wrap up this video, I want to talk about why this is useful. I think the best reason to download videos is that it lets you organize them how you want. I have a bunch of different folders of videos that I use for my learning, so that I'm good-confused, they don't get lost, and I don't need to log into YouTube and get distracted when I'm looking for a specific thing. Second, there are no ads. If you don't have YouTube Premium, you don't need to have your immersion time interrupted by annoying ads for something that you're not going to buy. You're still going to see the sponsors reads in the videos, but at least those are immersion time. The other reason that I like downloading videos is because it makes it really easy to make subtitles with free subtitles like AI. This uploaded the video to the site, and when it's your turn, the machine brain will do its best to make matching subtitles that are way better than the auto-youtube ones. They're not perfect mind you, but they're better than nothing. You can also use the files offline. If you live somewhere that doesn't have great internet, or are worried about it cutting out, or are going on vacation, or for whatever reason, having YouTube videos downloaded makes it much, much easier to immerse. There's no barrier to entry. You can even send the audio files to your phone and immerse again in the videos using the best podcast app video about that up in the corner. The final reason I like downloading videos, which is related to all the other ones, is that it reduces distractions and allows you to just use your own tools. You don't have to see all the comments, pop-up, suggested videos, and click around to shine what you need. The internet is a huge and distracting place, and so having to log in just when you want to watch a video and practice your target language can make it more difficult. You also have more control with your own tools. I like to use MPV player and vocabative, which are two of my favorites, to watch my videos. And so I found the downloading that makes it so much easier. Alright, I think I've blabbed on long enough. This video is already more techy than I'd like, but I hope that it helped you in some way. It's a tool I make a lot of use of in my own learning, so I hope that you try it out. Right down below the subscribe button is the description, which is full of useful links and guides to help you if you get stuck in the installation process. And don't forget to check out some of the other videos on our channel. There are lots of things for all sorts of different kinds of people. But until next time, happy immersing.

## Using google developer console API `youtube-vidoes-api`

## Setting Up API

In [ ]:
import os
import googleapiclient.discovery

# Set up the YouTube API client
api_service_name = "youtube"
api_version = "v3"
DEVELOPER_KEY = "Your API"

youtube = googleapiclient.discovery.build(api_service_name, api_version, developerKey=DEVELOPER_KEY)

- `query:` The search query string.

- `max_results` (optional): The maximum number of results to return, with a default value of 100.

- it creates a request object using `youtube.search().list():`

- The `request.execute()` method is called to execute the search request and retrieve the response.

- The `request.execute()` method is called to execute the search request and retrieve the response.

In [ ]:
def search_videos(query, max_results=100):
    request = youtube.search().list(
      q=query,
      part='snippet',
      type='video',
      videoCaption='closedCaption',
      relevanceLanguage='en',
      maxResults=max_results
    )
    response = request.execute()
    return response.get('items', [])

`collect_video_data` is to gather video data based on different sentiment categories (positive, negative, neutral). It uses a search function ( `search_videos`) to retrieve video information from a video platform API (like YouTube).

### Structure

1. **Queries Dictionary**: It defines three lists of search queries based on sentiment.

2. **Video Data Storage**: It initializes a dictionary to store video data categorized by sentiment.

3. **Search Loop**: It iterates through each sentiment category and its associated queries, performing a search for each query and collecting relevant video data.

### Key Components
- **`queries`**: A dictionary mapping sentiment categories to search queries.
- **`video_data`**: A dictionary initialized to hold lists of video data for each sentiment.
- **Nested Loops**: The outer loop iterates through sentiments, and the inner loop processes each search query.
- **Data Collection**: For each video result, it extracts the title, description, and video ID, appending this information to the appropriate list in `video_data`.

In [ ]:
def collect_video_data():

    queries = {
        'positive': ['motivational speech english', 'success story', 'inspirational talk','Positive message'],
        'negative': ['negative news', 'angry rant', 'critical review', 'gun voilence'],
        'neutral': ['tutorial', 'product description', 'informational video']
    }

    video_data = {'positive': [], 'negative': [], 'neutral': []}

    for sentiment, q_list in queries.items():
        for query in q_list:
            results = search_videos(query)
            for item in results:
                video_data[sentiment].append({
                    'title': item['snippet']['title'],
                    'description': item['snippet']['description'],
                    'videoId': item['id']['videoId']
                })

    return video_data

video_data = collect_video_data()

In [ ]:
# Print collected video data
for sentiment in video_data:
    print(f"\n{sentiment.capitalize()} videos:")
    for video in video_data[sentiment]:
        print(f"Title: {video['title']}, Video ID: {video['videoId']}")

Positive videos:
Title: FOCUS ON YOURSELF NOT OTHERS (motivational video), Video ID: eBSeCp__xhI
Title: DON&#39;T WASTE YOUR LIFE - Powerful Motivational Speech Video (Ft. Coach Pain), Video ID: -ESQmzDbnL8
Title: KILL YOUR EXCUSES - Motivational Speech, Video ID: JjvN_hYDp3g
Title: One of the Greatest Speeches Ever | Steve Jobs, Video ID: Tuw8hxrFBH8
Title: CONFIDENCE - Motivational Speech, Video ID: Xu1kbRUCRic
Title: Admiral McRaven Leaves the Audience SPEECHLESS | One of the Best Motivational Speeches, Video ID: TBuIGBCF9jc
Title: NEVER GIVE UP - Best Motivational Speech Video (Featuring Coach Pain), Video ID: 68IcEa2BRC8
Title: ENGLISH SPEECH | MUNIBA MAZARI: Motivational Words (English Subtitles), Video ID: r01DOmPpxjg
Title: Maadhyam IAS  #india #education #statepcs #civilserviceexam #facts #upsc #upscexam #mainssyllabus, Video ID: Fbol-RPcKOs
Title: Put God First - Denzel Washington Motivational &amp; Inspiring Commencement Speech, Video ID: BxY_eJLBflk
Title: I&#39;M GOING TO WIN - Best Motivational Speech Video (Featuring Denzel Washington), Video ID: ZC4eWrzxIqw
Title: DISCIPLINE YOURSELF - Motivational Speech, Video ID: vAvjQK6hnIk
Title: STOP WASTING TIME - Part 1 | Motivational Video for Success &amp; Studying (Ft. Coach Hite), Video ID: z3FA2kALScU
Title: How Long It Takes To Change Your Life? | Nwal Hadaki | TEDxSafirSchool, Video ID: g85WsxE1gAU
Title: ENGLISH SPEECH | MUNIBA MAZARI - We all are Perfectly Imperfect (English Subtitles), Video ID: fBnAMUkNM2k
Title: IT&#39;S TIME TO GET OVER IT! - Powerful Motivational Speech for Success - Les Brown Motivation, Video ID: ffXKVfUcQE8
Title: Denzel Washington&#39;s Speech Will Leave You SPEECHLESS - One of the Most Eye Opening Speeches Ever, Video ID: uM-MqsWjQd4
Title: How To Be Really Successful? | Sadhguru Answers, Video ID: ZhI-stDIlCE
Title: Dream - Motivational Video, Video ID: g-jwWYX7Jlo
Title: Why I Learned English | Jack Ma, Video ID: sDy07cIYrdg
Title: KILL YOUR LAZINESS - Motivational Speech, Video ID: V04ojClenZU
Title: Oprah Winfrey Motivation Speech | This 2 Minute Video Will Change Your Life, Video ID: nyhRNwTfydU
Title: THE POWER OF POSITIVITY - Best Motivational Video For Positive Thinking, Video ID: HwLK9dBQn0g
Title: ENGLISH SPEECH | PRIYANKA CHOPRA: Be Fearless (English Subtitles), Video ID: aDG1T0kJnd4
Title: Shah Rukh Khan Eye Opening Speech (english), Video ID: 126OF212iZs
Title: How to Stay Motivated All the Time? | Sadhguru Answers, Video ID: d8p-5WcXoRs
Title: The Power of Being Alone | Sadhguru Jaggi Vasudev, Video ID: Yiaatr-Noh0
Title: PROVE EVERYONE WRONG - Motivational Speech, Video ID: 2OJ4dczhqNY
Title: BECOME A MONSTER - Motivational Speech, Video ID: nNwGKCLbKL8
Title: ENGLISH SPEECH | JUSTIN TRUDEAU: We’re All the Same (English Subtitles), Video ID: 3AIoHLr8nTI
Title: They said Girls are WASTE OF MONEY  | Priyanka Chopra | Motivation | English Speech | WINNER GIRLS, Video ID: bZeOWYwcokQ
Title: PROVE THEM WRONG - Motivational Speech, Video ID: RGJwkP4HT7w
Title: DON&#39;T GIVE UP - Motivational Speech, Video ID: 37BJzFEeF2Q
Title: SELF LOVE | Positive Morning Motivation | LISTEN EVERY DAY!, Video ID: YuNLNeIorJw
Title: 20 Principles You Should Live By To Get Everything You Want In Life! - MASTER THIS!, Video ID: hn0Uk4YQv0Q
Title: LIFE IS SHORT - Best Motivational Speech Video (Featuring Coach Pain), Video ID: 0Znvum3WikA
Title: Jack Ma&#39;s Life Advice Will Change Your Life (MUST WATCH), Video ID: lYGGpc2mMno
Title: ENGLISH SPEECH | BARACK OBAMA: The People of India (English Subtitles), Video ID: S1dNuCG3sOA
Title: Why Do We Fall - Motivational Video, Video ID: mgmVOuLgFB0
Title: STAY FOCUSED ON YOUR DREAM - Motivational Speech, Video ID: X2Fz9xbmfOc
Title: Achieve Your Dreams with Jack Ma&#39;s Motivational Speech on Success in Career, Video ID: F1MR2Wg44GE
Title: SELF DISCIPLINE - Best Motivational Speech Video (Featuring Will Smith), Video ID: ft_DXwgUXB0
Title: NEVER GIVE UP - Best Motivational Speech Video 2020, Video ID: K4TfMeUxmK4
Title: The Most Inspiring Speech: 4 True Rules To Success | A. P. J. Abdul Kalam, Video ID: 3SDkzDlw1yc
Title: ENGLISH SPEECH | NICK VUJICIC: How to Stop A Bully (English Subtitles), Video ID: jkZizIN5aEg
Title: I MUST KEEP GOING - Powerful Motivational Speech on PERSPECTIVE (Featuring Marcus Elevation Taylor), Video ID: 23tusPiiNZk
Title: BELIEVE IN YOURSELF - Motivational Speech, Video ID: kz7n9JxHrN0
Title: ENGLISH SPEECH | IVANKA TRUMP: Think Big Again (English Subtitles), Video ID: _nUDuXRh3zM
Title: I CAN DO IT - Powerful Motivational Speech Video (Featuring Lisa Nichols), Video ID: tj7utbR4rMc
Title: Find a good boss - Jack Ma | Motivation, Video ID: 67GQRHm81j8
Title: Failing at Normal: An ADHD Success Story | Jessica McCabe | TEDxBratislava, Video ID: JiwZQNYlGQI
Title: Diabetes Weight Loss Success Story, Video ID: _5mckHMB4f0
Title: Conquering 20 years of anxiety and depression - Collaborative Care success story, Video ID: Xtd46y5D0rw
Title: Getting Pregnant with PCOS: Our Success Story, Video ID: lPS5wMuOj_A
Title: A weight loss success story – how one man worked with Charles D’Angelo and lost 160lbs!, Video ID: YBfxcibvqk8
Title: I got fired then miracles started happening. The success story of a single mother | LNN, Video ID: Ls6ZBbYJ1hk
Title: Knee Replacement Success Story (Lynn Sago), Video ID: gx4rDTa6oNM
Title: One of the Greatest Speeches Ever | Steve Jobs, Video ID: Tuw8hxrFBH8
Title: Meesho Success Story Case Study | What you can learn from Meesho Platform? | Game of Selling, Video ID: zVJ2KtgZVlw
Title: Multi-Millionaire Explains His Simple Steps to Self-Made Success, Video ID: o_GFl1lppdA
Title: My success story with Chuck Hicks, Video ID: ol4-LKdphUs
Title: Bariatric Surgery Success Story, Video ID: quymkkvU_6k
Title: Spinal Fusion Surgery Success Story, Video ID: wtId2olQGMw
Title: Martin&#39;s SURPRISING Tinnitus Success Story, Video ID: -M2ziJvjHJs
Title: My success story with Mitzi Champion, Video ID: nXFP73n0Plk
Title: ECT for Depression Patient Success Story, Video ID: j3p7DX_NB5k
Title: 43 Years of Migraines - Success Story, Video ID: y2rlmsEwOpI
Title: Chris&#39;s ACL Success Story, Video ID: qP3FX8hFqqI
Title: Jack Ma&#39;s Life Advice Will Change Your Life (MUST WATCH), Video ID: lYGGpc2mMno
Title: TMS Success Story - Facial Pain, Back Pain, Nerve and Joint Pain, Video ID: WYdvlSUZXvo
Title: Centria Autism | Sydni&#39;s Success Story, Video ID: 5bNgV4BCK-c
Title: How I Got My Life Back: Jackie’s Neck Revision Surgery Success Story (30s) - HSS, Video ID: paYKyFPeR0M
Title: YOUNG ENTREPRENEURS SUCCESS Story - Motivational Video, Video ID: j7wZogQhmFE
Title: Low AMH Treatment - THERE IS HOPE - Success story, Video ID: slfYP6LFrXA
Title: Holly&#39;s Success Story from Rheumatoid Arthritis, Video ID: _ceN-oZzj1g
Title: Why Pete Townshend’s Tinnitus Success Story Is So Important, Video ID: _iQW3AVtVnw
Title: Saving Joe - Tempus ALS customer success story | 3 minutes, Video ID: 4_hnW42CVMw
Title: Dual Lung Cancer Survivor Shares His Success Story, Video ID: xXpqtRpyp10
Title: Jim’s low carb success story, Video ID: V3ovFdGUZps
Title: TMS Success Story - Rebecca Tolin - CFS, Interstitial Cystitis, Brain Fog,  Fibromyalgia, Video ID: XT5GGzCfzcs
Title: Part 1- Autism Success Story of Sainyam🙋❤️🔆🧿 #autism, Video ID: BlqCg6ktwKI
Title: Fibromyalgia and Chronic Fatigue Success Story - Pain Free You, Video ID: om9nZyxfBmI
Title: Taking Control of Ménière’s Disease: Nancy&#39;s Success Story, Video ID: PFuvGAJ8x6s
Title: My low carb success story with Nathan Wiens, Video ID: l2GPpeMKNj0
Title: Bariatric surgery success story, Video ID: XeZoF0lIPEw
Title: IVF Pregnancy | An IVF Success Story at Sitaram Bhartia, Video ID: 8Rrx6szfUBI
Title: Jonathan&#39;s TMS Success Story - Sports Symptoms and Fibromyalgia, Video ID: 7EdXRReAeNs
Title: How I Got My Life Back: Danny’s Adult Scoliosis Surgery Success Story (60s), Video ID: OxDnDDrY0jM
Title: Chris&#39; Success Story (Meningioma) - Pacific Brain Tumor Center, Santa Monica, CA, Video ID: C-Vg0G1GKrA
Title: Julie&#39;s Varicose Vein Treatment Success Story - Vein Clinics of America, Video ID: vNpf5RzuMHY
Title: Before and after: New Orleans woman shares success story with keto diet, Video ID: OtXfBSEnSJc
Title: TMS Success Story - Pelvic Pain - Laura, Video ID: 24boeDYK5V0
Title: Universe Works In MYSTERIOUS Ways - Unexpected Success Stories | Manifestation Monday, Video ID: lLXpPNJxsyU
Title: Stem Cell Success Stories, Video ID: 2ng1jcoyub8
Title: Peer Coach Success Story: Reducing Antipsychotic Medications, Video ID: COpkCu5SV0s
Title: &quot;My reaction to it changed!!&quot; - Lynn&#39;s Tinnitus Success Story, Video ID: MfluyVpCDWs
Title: QNET Success Story | VC Mohannad Al Joraki, Video ID: 89onSjkFPzo
Title: Type I Diabetic Child&#39;s Amazing Success Story, Video ID: xG7b7WnzugQ
Title: Bone Density and Osteoporosis Success Story: Garrett - Atlantis Physical Therapy Torrance, Video ID: GyQO1ZRTZBc
Title: SIRPA Success Story Tommy - Prostatitis Pain, Video ID: 0N5ukKYj9Og
Title: One of the Greatest Speeches Ever | Steve Jobs, Video ID: Tuw8hxrFBH8
Title: Put God First - Denzel Washington Motivational &amp; Inspiring Commencement Speech, Video ID: BxY_eJLBflk
Title: GIVE IT TO GOD | Stop Worrying &amp; Trust God - Inspirational &amp; Motivational Video, Video ID: FZimOSrRJN0
Title: Admiral McRaven Leaves the Audience SPEECHLESS | One of the Best Motivational Speeches, Video ID: TBuIGBCF9jc
Title: TRUST THAT GOD IS IN CONTROL | 1 Hour Powerful Christian Motivation - Inspirational &amp; Motivational, Video ID: ydZAcANvrkY
Title: कर्म भाग्य से कहीं, बड़ा होता है | Powerful Krishna Motivational Speech | krishna motivation, Video ID: Hjh2BmTYpq4
Title: Goalcast&#39;s Top 10 Most Epic Inspirational Speeches  | Vol.2, Video ID: _U7mshkeH20
Title: GOD HAS A PLAN FOR YOU | Chadwick Boseman - Inspirational &amp; Motivational Speech, Video ID: DoA-a-g2o4g
Title: It&#39;s a Great Day to Be Alive | Ian Humphrey Inspirational Speech| Goalcast, Video ID: mRR_hNtFJeE
Title: Dream - Motivational Video, Video ID: g-jwWYX7Jlo
Title: THE GREATEST LOVE STORY EVER TOLD | Powerful Billy Graham Speech - Inspirational Motivational Video, Video ID: tIIn6tyk-hQ
Title: The Greatest - Muhammad Ali Inspirational Video, Video ID: V2EfL1j4KYE
Title: LIFE IS SHORT | Live Every Day for God - Billy Graham Inspirational &amp; Motivational Video, Video ID: HhBNGdS5Kqk
Title: Hawaii in 4K - Inspirational Speech - Make Your Life Extraordinary!, Video ID: L3V7LKYPIUQ
Title: Kobe Bryant - Inspirational Video, Video ID: JHVMW3U5BZE
Title: LIVE A LIFE OF SIGNIFICANCE | Live For Jesus - Tim Tebow Inspirational &amp; Motivational Speech, Video ID: ZtZx72ma6Uk
Title: TRAGEDY INTO TRIUMPH | When God Says No - Inky Johnson Inspirational &amp; Motivational Video, Video ID: KjJXB2Zkxgo
Title: One Of The Most Inspirational Talks Ever - Rodney Mullen | THE TRUTH, Video ID: i6Sla-RZ5Ts
Title: Jack Ma Motivational Video | Believe In Your Dreams | Inspirational Speech | Startup Stories, Video ID: X9JExlvPwcs
Title: WHEN YOUR HEART IS BROKEN | God Loves The Broken - Inspirational &amp; Motivational Video, Video ID: D6RxkaL3ZP0
Title: Make An Impact - Inspirational Video, Video ID: pb7_YJp9bVA
Title: STICK WITH GOD | Denzel Washington Inspirational &amp; Motivational Speech, Video ID: 5H9o3avuVlY
Title: How to Prove Others Wrong | Jonathan Mooney Inspirational Speech | Goalcast, Video ID: 6nmXrSvewRA
Title: Ernie&#39;s Inspirational Speech To Bama&#39;s Football Team | Remembering Michael Johnson | NBA on TNT, Video ID: og6CffsHqf8
Title: Elon Musk Motivational Video | Inspirational Speech | Never Give Up | Startup Stories, Video ID: OCV5F88TYnk
Title: Ray Lewis Inspirational Speech   Stanford Basketball @ NIT, Video ID: aCVO0RLUP-k
Title: SEEK GOD FIRST | 1 Hour Powerful Motivation - Inspirational &amp; Motivational Video, Video ID: sJEDfAbuutA
Title: After watching this, your brain will not be the same | Lara Boyd | TEDxVancouver, Video ID: LNHBMFCzznE
Title: BILLY GRAHAM | The Speech That Will Change Your Life Forever - Inspirational &amp; Motivational Video, Video ID: V6ujbmidGPY
Title: THE POWER OF PRAYER | Connect With God - Inspirational &amp; Motivational Video, Video ID: hbk70u5o4Lc
Title: TRUST GOD | 1 Hour Powerful Christian Motivation - Inspirational &amp; Motivational Video, Video ID: 0VI57viMdps
Title: BE ANXIOUS FOR NOTHING | Overcoming Anxiety &amp; Worry - Inspirational &amp; Motivational Video, Video ID: psQkuax3xj0
Title: Steve Jobs Motivational Speech | Inspirational Video | Entrepreneur Motivation | Startup Stories, Video ID: ptD0T-ZcF2M
Title: START WITH GOD | 1 Hour Powerful Motivation - Inspirational &amp; Motivational Video, Video ID: dB18p5JiFfY
Title: DON&#39;T QUIT, IT&#39;S POSSIBLE ! - Football Motivation - Inspirational Video - Nihaldinho Official, Video ID: mAQP5ASH-BA
Title: How To Write An Inspirational Speech, Video ID: UuTimNRf1Tw
Title: DON’T QUIT | Trust God When Times Are Hard - Inspirational &amp; Motivational Video, Video ID: O1SZ9DlhV8A
Title: Joel Osteen - 10 Minutes to Start Your Day Right! (MORNING MOTIVATION) Inspirational &amp; Motivational, Video ID: TgjDOxEAYJU
Title: God’s Plan For Your Life - Nick Vujicic Inspirational &amp; Motivational Video, Video ID: beeaXdv_mGg
Title: Taking Control of Your Life’s Destiny | How-to-Live Inspirational Talk, Video ID: Q6M3xbHvNaw
Title: DON’T QUIT ! - Hockey Motivation - Inspirational Video, Video ID: 5sXfHmdFYoU
Title: OVERCOMING THE PAST | Letting Go of Hurt - Inspirational &amp; Motivational Video, Video ID: EzbEcV-l7ok
Title: Growing in Faith and Unconditional Love | How-to-Live Inspirational Talk, Video ID: 76zo-lHzLGU
Title: BE KIND - Inspirational &amp; Motivational Video, Video ID: NXkJ9eNpWNw
Title: WALK BY FAITH | Trust God Even When You Don’t Understand - Inspirational &amp; Motivational Video, Video ID: yvhQxFIGCP4
Title: THE POWER OF POSITIVITY - Best Motivational Video For Positive Thinking, Video ID: HwLK9dBQn0g
Title: BEGIN YOUR DAY WITH GOD | Listen To This Before You Start Your Day - Morning Inspiration, Video ID: 2IJLvgF8vEI
Title: The Reflection in Me HD, Video ID: D9OOXCu5XMg
Title: Positive Affirmations for Peace and Calm | Reduce Stress &amp; Anxiety, Video ID: oS6KlpzDNS0
Title: Dr Wayne Dyer - 5 Minutes Before You Fall Asleep - Positive Affirmations - Wayne Dyer  Meditation -, Video ID: Kvs-_22lwjA
Title: FOCUS ON YOURSELF NOT OTHERS (motivational video), Video ID: eBSeCp__xhI
Title: Brainerd teen goes viral with positive message delivered via doorbell camera, Video ID: lSPr6OUQGgo
Title: A positive message, Video ID: 8L2_0G8epD0
Title: God Message now : Everthing Will be Alright My Child | God Says | God Message Today, Video ID: DfHgcsp2_5Y
Title: Thank You Universe Affirmations | Affirmations For Positive Thinking | Gratitude, Success, Abundance, Video ID: HeV3UeUumT8
Title: SELF LOVE | Positive Morning Motivation | LISTEN EVERY DAY!, Video ID: YuNLNeIorJw
Title: START FRESH EVERY DAY | Wake Up With A Positive Attitude - Morning Inspiration to Motivate Your Day, Video ID: cuFZ3NUwiPQ
Title: ‘Her message is perfect for this moment’: VP Harris has flipped the 2024 election on its head, Video ID: j7gXyPYYyLY
Title: Coat Your Mind In Positive Thinking | Motivated, Video ID: KWFZxOEGPx4
Title: GIVE IT TO GOD | Stop Worrying &amp; Trust God - Inspirational &amp; Motivational Video, Video ID: FZimOSrRJN0
Title: Discovering God&#39;s Positive Message The Key to Happiness #shorts #jesus #godmessage #jesuschrist, Video ID: mm0dKd1UrXE
Title: A Positive Message From Pope Francis, Video ID: -SVfh3C85jU
Title: How to Remove Negative Thoughts? Sadhguru Jagadish Vasudev Answers, Video ID: lJCUC0mRkPo
Title: &quot;It Goes Straight to Your Subconscious Mind&quot; - &quot;I AM&quot; Affirmations For Success, Wealth &amp; Happiness, Video ID: hKqjSiM38uM
Title: START YOUR DAY WITH HAPPINESS | Every Day Decide To Be Happy - Morning Inspiration To Motivate You, Video ID: Qt74g5FYHTw
Title: Never give up , Believe in yourself!, Video ID: 3CQusoJSh0E
Title: Local barbershop creates video to send positive message, Video ID: es81E_ztEEQ
Title: A positive message for Independent Artists…, Video ID: -V4bWprbh6Q
Title: WAKE UP AND START YOUR DAY WITH GOD | Listen To This Every Day - Morning Inspiration, Video ID: zJt0e8FRBwM
Title: The Universe&#39;s Positive Message for Our Future - Break Through Fear Reading, Video ID: ldytfQ6BXA8
Title: The Fey| A Positive Message, Video ID: TtxEm9pbvZw
Title: &quot;That Is Your Testimony&quot; - Positive Message (Audio), Video ID: -uGjKBRpkUE
Title: Evansville family shares positive message for medical staff, Video ID: Eup2soMEdH8
Title: Embracing God&#39;s Positive Message #shorts #godmessage #god #christianity, Video ID: T0Rc0oZSUF0
Title: &#39;Pianos for Peace&#39; brings positive message to metro Atlanta, Video ID: hcPSyqMoBmQ
Title: TRUST THAT GOD IS IN CONTROL | 1 Hour Powerful Christian Motivation - Inspirational &amp; Motivational, Video ID: ydZAcANvrkY
Title: Abundance Mindset | Powerful Positive Affirmations | Morning Gratitude for Positivity &amp; Abundance, Video ID: hFtEC-AzBwM
Title: &#39;Chester Trio&#39; spreads positive message, sings at Union game, Video ID: 43Xx_7LMa9k
Title: Feeling Powerless? Stressed? A Positive Message from Prof Wolff - Economic Update, Video ID: xw1IXZhxWPI
Title: &quot;Hope Design&quot; founder turned college project into clothing company with positive message, Video ID: yUXPLX2RjqA
Title: SWLA cancer survivors honor Ben Terry’s legacy, positive message, Video ID: AKeknh2-_1s
Title: Local Girl Scout giving positive message through bracelets, Video ID: NA1kPQ5H5uc
Title: Sending a positive message through a new book, Video ID: lJ_vuBupFz0
Title: ‘Bringing the fight to Trump&#39;: How VP Kamala Harris candidacy has energized American politics, Video ID: 8XQToSRTTLE
Title: #SendTheLove: Valley neighborhood comes together to share positive message, Video ID: qNIqhbm_viU
Title: Supaman shares positive message with community, Video ID: ATDv200w3aw
Title: Pataskala residents stand-up for police officers with positive message, Video ID: knJJ9Aq_Dqg
Title: Albuquerque flower shop uses inventory to spread positive message, Video ID: vREmvkFKuzU
Title: Alleged bank robber spreads positive message when taken into custody, Video ID: xWxqCRU29xs
Title: Black History 210: Conductor uses music to spread positive message, Video ID: NYYhOZAmxo8
Title: Former Detroit gang leader uses second chance to help spread positive message, Video ID: Ey5YOe0hsHk
Title: The Republicans need to focus on a positive message | Roma Daravi | &#39;American Agenda&#39;, Video ID: Ko2GCavRe2w
Title: God&#39;s Positive Message: Transforming Lives with Love and Hope #shorts #godmessage #jesuschrist, Video ID: 5GfeGlBfLa4
Title: A Pep Talk from Kid President to You, Video ID: l-gQLqv9f4o
Title: &#39;Roanoke is resilient&#39;, Mayor Lea sends positive message at State of the City address, Video ID: 3iDNvHv_sHY

Negative videos:
Title: Trump Losing again? 45’s nightmare comes true as his nemesis Obama backs Kamala Harris, Video ID: Ao0bmNrRWhw
Title: The System that Fuels Media Negativity, Video ID: 89FoKRtpAy4
Title: Are Republican voters having doubts about Vance? Analyst breaks down the data, Video ID: 3SD9swv7HZA
Title: TRUMP FAIL: JD Vance 1st VP with negative favorability in 44 years, Video ID: -s0fXBQXSsA
Title: WATCH: Trump rally FULL SPEECH at St Cloud campaign event | LiveNOW from FOX, Video ID: -4Drs2TmEhc
Title: Here&#39;s why I stopped watching the news, Video ID: SGmAIaN4PPM
Title: Voters noticing more and more negative campaign ads in St. Johns County races, Video ID: dh6BPhgrOlU
Title: Las Vegas Raiders in foul mood after sports analysts negative predictions, Video ID: JPtKnRnPuMs
Title: Budget 2024 highlights | Impact on Stock Market | CA Rachana Ranade, Video ID: 7aqg9P9c2YM

### Writing the data in a json File

In [ ]:
# Save the video data to a JSON file
import json

with open('youtube_video_data.json', 'w') as f:
    json.dump(video_data, f, indent=4)

## youtube-transcript-api

This Api will used the video IDs to get the transcript of the videos

In [ ]:
!pip install youtube-transcript-api

Collecting youtube-transcript-api
  Downloading youtube_transcript_api-0.6.2-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from youtube-transcript-api) (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->youtube-transcript-api) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->youtube-transcript-api) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->youtube-transcript-api) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->youtube-transcript-api) (2024.7.4)
Downloading youtube_transcript_api-0.6.2-py3-none-any.whl (24 kB)
Installing collected packages: youtube-transcript-api
Successfully installed youtube-transcript-api-0.6.2

In [ ]:
from youtube_transcript_api import YouTubeTranscriptApi

def get_transcript(video_id):
  try:
    transcript = YouTubeTranscriptApi.get_transcript(video_id, languages=['en'])
    return " ".join([entry['text'] for entry in transcript])

  except Exception as e:
    print(f"Could not retrieve transcript for video ID {video_id}: {e}")
    return None

### Update the video data with transcripts

In [ ]:
for sentiment in video_data:
    for video in video_data[sentiment]:
        transcript = get_transcript(video['videoId'])
        video['transcript'] = transcript

# Save the updated video data with transcripts to a JSON file
with open('youtube_video_data_with_transcripts.json', 'w') as f:
    json.dump(video_data, f, indent=4)

Could not retrieve transcript for video ID Fbol-RPcKOs:
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=Fbol-RPcKOs! This is most likely caused by:

No transcripts were found for any of the requested language codes: ['en']

For this video (Fbol-RPcKOs) transcripts are available in the following languages:

(MANUALLY CREATED)
 - hi ("Hindi")[TRANSLATABLE]

(GENERATED)
 - hi ("Hindi (auto-generated)")[TRANSLATABLE]

(TRANSLATION LANGUAGES)
 - af ("Afrikaans")
 - ak ("Akan")
 - sq ("Albanian")
 - am ("Amharic")
 - ar ("Arabic")
 - hy ("Armenian")
 - as ("Assamese")
 - ay ("Aymara")
 - az ("Azerbaijani")
 - bn ("Bangla")
 - eu ("Basque")
 - be ("Belarusian")
 - bho ("Bhojpuri")
 - bs ("Bosnian")
 - bg ("Bulgarian")
 - my ("Burmese")
 - ca ("Catalan")
 - ceb ("Cebuano")
 - zh-Hans ("Chinese (Simplified)")
 - zh-Hant ("Chinese (Traditional)")
 - co ("Corsican")
 - hr ("Croatian")
 - cs ("Czech")
 - da ("Danish")
 - dv ("Divehi")
 - nl ("Dutch")
 - en ("English")
 - eo ("Esperanto")
 - et ("Estonian")
 - ee ("Ewe")
 - fil ("Filipino")
 - fi ("Finnish")
 - fr ("French")
 - gl ("Galician")
 - lg ("Ganda")
 - ka ("Georgian")
 - de ("German")
 - el ("Greek")
 - gn ("Guarani")
 - gu ("Gujarati")
 - ht ("Haitian Creole")
 - ha ("Hausa")
 - haw ("Hawaiian")
 - iw ("Hebrew")
 - hi ("Hindi")
 - hmn ("Hmong")
 - hu ("Hungarian")
 - is ("Icelandic")
 - ig ("Igbo")
 - id ("Indonesian")
 - ga ("Irish")
 - it ("Italian")
 - ja ("Japanese")
 - jv ("Javanese")
 - kn ("Kannada")
 - kk ("Kazakh")
 - km ("Khmer")
 - rw ("Kinyarwanda")
 - ko ("Korean")
 - kri ("Krio")
 - ku ("Kurdish")
 - ky ("Kyrgyz")
 - lo ("Lao")
 - la ("Latin")
 - lv ("Latvian")
 - ln ("Lingala")
 - lt ("Lithuanian")
 - lb ("Luxembourgish")
 - mk ("Macedonian")
 - mg ("Malagasy")
 - ms ("Malay")
 - ml ("Malayalam")
 - mt ("Maltese")
 - mi ("Māori")
 - mr ("Marathi")
 - mn ("Mongolian")
 - ne ("Nepali")
 - nso ("Northern Sotho")
 - no ("Norwegian")
 - ny ("Nyanja")
 - or ("Odia")
 - om ("Oromo")
 - ps ("Pashto")
 - fa ("Persian")
 - pl ("Polish")
 - pt ("Portuguese")
 - pa ("Punjabi")
 - qu ("Quechua")
 - ro ("Romanian")
 - ru ("Russian")
 - sm ("Samoan")
 - sa ("Sanskrit")
 - gd ("Scottish Gaelic")
 - sr ("Serbian")
 - sn ("Shona")
 - sd ("Sindhi")
 - si ("Sinhala")
 - sk ("Slovak")
 - sl ("Slovenian")
 - so ("Somali")
 - st ("Southern Sotho")
 - es ("Spanish")
 - su ("Sundanese")
 - sw ("Swahili")
 - sv ("Swedish")
 - tg ("Tajik")
 - ta ("Tamil")
 - tt ("Tatar")
 - te ("Telugu")
 - th ("Thai")
 - ti ("Tigrinya")
 - ts ("Tsonga")
 - tr ("Turkish")
 - tk ("Turkmen")
 - uk ("Ukrainian")
 - ur ("Urdu")
 - ug ("Uyghur")
 - uz ("Uzbek")
 - vi ("Vietnamese")
 - cy ("Welsh")
 - fy ("Western Frisian")
 - xh ("Xhosa")
 - yi ("Yiddish")
 - yo ("Yoruba")
 - zu ("Zulu")

If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!
Could not retrieve transcript for video ID ZhI-stDIlCE:
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=ZhI-stDIlCE! This is most likely caused by:

No transcripts were found for any of the requested language codes: ['en']

For this video (ZhI-stDIlCE) transcripts are available in the following languages:

(MANUALLY CREATED)
 - en-US ("English (United States)")[TRANSLATABLE]
 - ko ("Korean")[TRANSLATABLE]
 - pt-BR ("Portuguese (Brazil)")[TRANSLATABLE]

(GENERATED)
None

(TRANSLATION LANGUAGES)
 - af ("Afrikaans")
 - ak ("Akan")
 - sq ("Albanian")
 - am ("Amharic")
 - ar ("Arabic")
 - hy ("Armenian")
 - as ("Assamese")
 - ay ("Aymara")
 - az ("Azerbaijani")
 - bn ("Bangla")
 - eu ("Basque")
 - be ("Belarusian")
 - bho ("Bhojpuri")
 - bs ("Bosnian")
 - bg ("Bulgarian")
 - my ("Burmese")
 - ca ("Catalan")
 - ceb ("Cebuano")
 - zh-Hans ("Chinese (Simplified)")
 - zh-Hant ("Chinese (Traditional)")
 - co ("Corsican")
 - hr ("Croatian")
 - cs ("Czech")
 - da ("Danish")
 - dv ("Divehi")
 - nl ("Dutch")
 - en ("English")
 - eo ("Esperanto")
 - et ("Estonian")
 - ee ("Ewe")
 - fil ("Filipino")
 - fi ("Finnish")
 - fr ("French")
 - gl ("Galician")
 - lg ("Ganda")
 - ka ("Georgian")
 - de ("German")
 - el ("Greek")
 - gn ("Guarani")
 - gu ("Gujarati")
 - ht ("Haitian Creole")
 - ha ("Hausa")
 - haw ("Hawaiian")
 - iw ("Hebrew")
 - hi ("Hindi")
 - hmn ("Hmong")
 - hu ("Hungarian")
 - is ("Icelandic")
 - ig ("Igbo")
 - id ("Indonesian")
 - ga ("Irish")
 - it ("Italian")
 - ja ("Japanese")
 - jv ("Javanese")
 - kn ("Kannada")
 - kk ("Kazakh")
 - km ("Khmer")
 - rw ("Kinyarwanda")
 - ko ("Korean")
 - kri ("Krio")
 - ku ("Kurdish")
 - ky ("Kyrgyz")
 - lo ("Lao")
 - la ("Latin")
 - lv ("Latvian")
 - ln ("Lingala")
 - lt ("Lithuanian")
 - lb ("Luxembourgish")
 - mk ("Macedonian")
 - mg ("Malagasy")
 - ms ("Malay")
 - ml ("Malayalam")
 - mt ("Maltese")
 - mi ("Māori")
 - mr ("Marathi")
 - mn ("Mongolian")
 - ne ("Nepali")
 - nso ("Northern Sotho")
 - no ("Norwegian")
 - ny ("Nyanja")
 - or ("Odia")
 - om ("Oromo")
 - ps ("Pashto")
 - fa ("Persian")
 - pl ("Polish")
 - pt ("Portuguese")
 - pa ("Punjabi")
 - qu ("Quechua")
 - ro ("Romanian")
 - ru ("Russian")
 - sm ("Samoan")
 - sa ("Sanskrit")
 - gd ("Scottish Gaelic")
 - sr ("Serbian")
 - sn ("Shona")
 - sd ("Sindhi")
 - si ("Sinhala")
 - sk ("Slovak")
 - sl ("Slovenian")
 - so ("Somali")
 - st ("Southern Sotho")
 - es ("Spanish")
 - su ("Sundanese")
 - sw ("Swahili")
 - sv ("Swedish")
 - tg ("Tajik")
 - ta ("Tamil")
 - tt ("Tatar")
 - te ("Telugu")
 - th ("Thai")
 - ti ("Tigrinya")
 - ts ("Tsonga")
 - tr ("Turkish")
 - tk ("Turkmen")
 - uk ("Ukrainian")
 - ur ("Urdu")
 - ug ("Uyghur")
 - uz ("Uzbek")
 - vi ("Vietnamese")
 - cy ("Welsh")
 - fy ("Western Frisian")
 - xh ("Xhosa")
 - yi ("Yiddish")
 - yo ("Yoruba")
 - zu ("Zulu")

If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!
Could not retrieve transcript for video ID hn0Uk4YQv0Q:
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=hn0Uk4YQv0Q! This is most likely caused by:

No transcripts were found for any of the requested language codes: ['en']

For this video (hn0Uk4YQv0Q) transcripts are available in the following languages:

(MANUALLY CREATED)
 - vi ("Vietnamese")[TRANSLATABLE]

(GENERATED)
None

(TRANSLATION LANGUAGES)
 - af ("Afrikaans")
 - ak ("Akan")
 - sq ("Albanian")
 - am ("Amharic")
 - ar ("Arabic")
 - hy ("Armenian")
 - as ("Assamese")
 - ay ("Aymara")
 - az ("Azerbaijani")
 - bn ("Bangla")
 - eu ("Basque")
 - be ("Belarusian")
 - bho ("Bhojpuri")
 - bs ("Bosnian")
 - bg ("Bulgarian")
 - my ("Burmese")
 - ca ("Catalan")
 - ceb ("Cebuano")
 - zh-Hans ("Chinese (Simplified)")
 - zh-Hant ("Chinese (Traditional)")
 - co ("Corsican")
 - hr ("Croatian")
 - cs ("Czech")
 - da ("Danish")
 - dv ("Divehi")
 - nl ("Dutch")
 - en ("English")
 - eo ("Esperanto")
 - et ("Estonian")
 - ee ("Ewe")
 - fil ("Filipino")
 - fi ("Finnish")
 - fr ("French")
 - gl ("Galician")
 - lg ("Ganda")
 - ka ("Georgian")
 - de ("German")
 - el ("Greek")
 - gn ("Guarani")
 - gu ("Gujarati")
 - ht ("Haitian Creole")
 - ha ("Hausa")
 - haw ("Hawaiian")
 - iw ("Hebrew")
 - hi ("Hindi")
 - hmn ("Hmong")
 - hu ("Hungarian")
 - is ("Icelandic")
 - ig ("Igbo")
 - id ("Indonesian")
 - ga ("Irish")
 - it ("Italian")
 - ja ("Japanese")
 - jv ("Javanese")
 - kn ("Kannada")
 - kk ("Kazakh")
 - km ("Khmer")
 - rw ("Kinyarwanda")
 - ko ("Korean")
 - kri ("Krio")
 - ku ("Kurdish")
 - ky ("Kyrgyz")
 - lo ("Lao")
 - la ("Latin")
 - lv ("Latvian")
 - ln ("Lingala")
 - lt ("Lithuanian")
 - lb ("Luxembourgish")
 - mk ("Macedonian")
 - mg ("Malagasy")
 - ms ("Malay")
 - ml ("Malayalam")
 - mt ("Maltese")
 - mi ("Māori")
 - mr ("Marathi")
 - mn ("Mongolian")
 - ne ("Nepali")
 - nso ("Northern Sotho")
 - no ("Norwegian")
 - ny ("Nyanja")
 - or ("Odia")
 - om ("Oromo")
 - ps ("Pashto")
 - fa ("Persian")
 - pl ("Polish")
 - pt ("Portuguese")
 - pa ("Punjabi")
 - qu ("Quechua")
 - ro ("Romanian")
 - ru ("Russian")
 - sm ("Samoan")
 - sa ("Sanskrit")
 - gd ("Scottish Gaelic")
 - sr ("Serbian")
 - sn ("Shona")
 - sd ("Sindhi")
 - si ("Sinhala")
 - sk ("Slovak")
 - sl ("Slovenian")
 - so ("Somali")
 - st ("Southern Sotho")
 - es ("Spanish")
 - su ("Sundanese")
 - sw ("Swahili")
 - sv ("Swedish")
 - tg ("Tajik")
 - ta ("Tamil")
 - tt ("Tatar")
 - te ("Telugu")
 - th ("Thai")
 - ti ("Tigrinya")
 - ts ("Tsonga")
 - tr ("Turkish")
 - tk ("Turkmen")
 - uk ("Ukrainian")
 - ur ("Urdu")
 - ug ("Uyghur")
 - uz ("Uzbek")
 - vi ("Vietnamese")
 - cy ("Welsh")
 - fy ("Western Frisian")
 - xh ("Xhosa")
 - yi ("Yiddish")
 - yo ("Yoruba")
 - zu ("Zulu")

If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!
Could not retrieve transcript for video ID S1dNuCG3sOA:
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=S1dNuCG3sOA! This is most likely caused by:

No transcripts were found for any of the requested language codes: ['en']

For this video (S1dNuCG3sOA) transcripts are available in the following languages:

(MANUALLY CREATED)
 - ar ("Arabic")[TRANSLATABLE]
 - hi ("Hindi")[TRANSLATABLE]
 - id ("Indonesian")[TRANSLATABLE]
 - pt ("Portuguese")[TRANSLATABLE]
 - pa ("Punjabi")[TRANSLATABLE]
 - es ("Spanish")[TRANSLATABLE]
 - vi ("Vietnamese")[TRANSLATABLE]

(GENERATED)
None

(TRANSLATION LANGUAGES)
 - af ("Afrikaans")
 - ak ("Akan")
 - sq ("Albanian")
 - am ("Amharic")
 - ar ("Arabic")
 - hy ("Armenian")
 - as ("Assamese")
 - ay ("Aymara")
 - az ("Azerbaijani")
 - bn ("Bangla")
 - eu ("Basque")
 - be ("Belarusian")
 - bho ("Bhojpuri")
 - bs ("Bosnian")
 - bg ("Bulgarian")
 - my ("Burmese")
 - ca ("Catalan")
 - ceb ("Cebuano")
 - zh-Hans ("Chinese (Simplified)")
 - zh-Hant ("Chinese (Traditional)")
 - co ("Corsican")
 - hr ("Croatian")
 - cs ("Czech")
 - da ("Danish")
 - dv ("Divehi")
 - nl ("Dutch")
 - en ("English")
 - eo ("Esperanto")
 - et ("Estonian")
 - ee ("Ewe")
 - fil ("Filipino")
 - fi ("Finnish")
 - fr ("French")
 - gl ("Galician")
 - lg ("Ganda")
 - ka ("Georgian")
 - de ("German")
 - el ("Greek")
 - gn ("Guarani")
 - gu ("Gujarati")
 - ht ("Haitian Creole")
 - ha ("Hausa")
 - haw ("Hawaiian")
 - iw ("Hebrew")
 - hi ("Hindi")
 - hmn ("Hmong")
 - hu ("Hungarian")
 - is ("Icelandic")
 - ig ("Igbo")
 - id ("Indonesian")
 - ga ("Irish")
 - it ("Italian")
 - ja ("Japanese")
 - jv ("Javanese")
 - kn ("Kannada")
 - kk ("Kazakh")
 - km ("Khmer")
 - rw ("Kinyarwanda")
 - ko ("Korean")
 - kri ("Krio")
 - ku ("Kurdish")
 - ky ("Kyrgyz")
 - lo ("Lao")
 - la ("Latin")
 - lv ("Latvian")
 - ln ("Lingala")
 - lt ("Lithuanian")
 - lb ("Luxembourgish")
 - mk ("Macedonian")
 - mg ("Malagasy")
 - ms ("Malay")
 - ml ("Malayalam")
 - mt ("Maltese")
 - mi ("Māori")
 - mr ("Marathi")
 - mn ("Mongolian")
 - ne ("Nepali")
 - nso ("Northern Sotho")
 - no ("Norwegian")
 - ny ("Nyanja")
 - or ("Odia")
 - om ("Oromo")
 - ps ("Pashto")
 - fa ("Persian")
 - pl ("Polish")
 - pt ("Portuguese")
 - pa ("Punjabi")
 - qu ("Quechua")
 - ro ("Romanian")
 - ru ("Russian")
 - sm ("Samoan")
 - sa ("Sanskrit")
 - gd ("Scottish Gaelic")
 - sr ("Serbian")
 - sn ("Shona")
 - sd ("Sindhi")
 - si ("Sinhala")
 - sk ("Slovak")
 - sl ("Slovenian")
 - so ("Somali")
 - st ("Southern Sotho")
 - es ("Spanish")
 - su ("Sundanese")
 - sw ("Swahili")
 - sv ("Swedish")
 - tg ("Tajik")
 - ta ("Tamil")
 - tt ("Tatar")
 - te ("Telugu")
 - th ("Thai")
 - ti ("Tigrinya")
 - ts ("Tsonga")
 - tr ("Turkish")
 - tk ("Turkmen")
 - uk ("Ukrainian")
 - ur ("Urdu")
 - ug ("Uyghur")
 - uz ("Uzbek")
 - vi ("Vietnamese")
 - cy ("Welsh")
 - fy ("Western Frisian")
 - xh ("Xhosa")
 - yi ("Yiddish")
 - yo ("Yoruba")
 - zu ("Zulu")

If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!
Could not retrieve transcript for video ID jkZizIN5aEg:
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=jkZizIN5aEg! This is most likely caused by:

Subtitles are disabled for this video

If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!
Could not retrieve transcript for video ID kz7n9JxHrN0: no element found: line 1, column 0
Could not retrieve transcript for video ID zVJ2KtgZVlw:
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=zVJ2KtgZVlw! This is most likely caused by:

No transcripts were found for any of the requested language codes: ['en']

For this video (zVJ2KtgZVlw) transcripts are available in the following languages:

(MANUALLY CREATED)
 - hi ("Hindi")[TRANSLATABLE]

(GENERATED)
 - hi ("Hindi (auto-generated)")[TRANSLATABLE]

(TRANSLATION LANGUAGES)
 - af ("Afrikaans")
 - ak ("Akan")
 - sq ("Albanian")
 - am ("Amharic")
 - ar ("Arabic")
 - hy ("Armenian")
 - as ("Assamese")
 - ay ("Aymara")
 - az ("Azerbaijani")
 - bn ("Bangla")
 - eu ("Basque")
 - be ("Belarusian")
 - bho ("Bhojpuri")
 - bs ("Bosnian")
 - bg ("Bulgarian")
 - my ("Burmese")
 - ca ("Catalan")
 - ceb ("Cebuano")
 - zh-Hans ("Chinese (Simplified)")
 - zh-Hant ("Chinese (Traditional)")
 - co ("Corsican")
 - hr ("Croatian")
 - cs ("Czech")
 - da ("Danish")
 - dv ("Divehi")
 - nl ("Dutch")
 - en ("English")
 - eo ("Esperanto")
 - et ("Estonian")
 - ee ("Ewe")
 - fil ("Filipino")
 - fi ("Finnish")
 - fr ("French")
 - gl ("Galician")
 - lg ("Ganda")
 - ka ("Georgian")
 - de ("German")
 - el ("Greek")
 - gn ("Guarani")
 - gu ("Gujarati")
 - ht ("Haitian Creole")
 - ha ("Hausa")
 - haw ("Hawaiian")
 - iw ("Hebrew")
 - hi ("Hindi")
 - hmn ("Hmong")
 - hu ("Hungarian")
 - is ("Icelandic")
 - ig ("Igbo")
 - id ("Indonesian")
 - ga ("Irish")
 - it ("Italian")
 - ja ("Japanese")
 - jv ("Javanese")
 - kn ("Kannada")
 - kk ("Kazakh")
 - km ("Khmer")
 - rw ("Kinyarwanda")
 - ko ("Korean")
 - kri ("Krio")
 - ku ("Kurdish")
 - ky ("Kyrgyz")
 - lo ("Lao")
 - la ("Latin")
 - lv ("Latvian")
 - ln ("Lingala")
 - lt ("Lithuanian")
 - lb ("Luxembourgish")
 - mk ("Macedonian")
 - mg ("Malagasy")
 - ms ("Malay")
 - ml ("Malayalam")
 - mt ("Maltese")
 - mi ("Māori")
 - mr ("Marathi")
 - mn ("Mongolian")
 - ne ("Nepali")
 - nso ("Northern Sotho")
 - no ("Norwegian")
 - ny ("Nyanja")
 - or ("Odia")
 - om ("Oromo")
 - ps ("Pashto")
 - fa ("Persian")
 - pl ("Polish")
 - pt ("Portuguese")
 - pa ("Punjabi")
 - qu ("Quechua")
 - ro ("Romanian")
 - ru ("Russian")
 - sm ("Samoan")
 - sa ("Sanskrit")
 - gd ("Scottish Gaelic")
 - sr ("Serbian")
 - sn ("Shona")
 - sd ("Sindhi")
 - si ("Sinhala")
 - sk ("Slovak")
 - sl ("Slovenian")
 - so ("Somali")
 - st ("Southern Sotho")
 - es ("Spanish")
 - su ("Sundanese")
 - sw ("Swahili")
 - sv ("Swedish")
 - tg ("Tajik")
 - ta ("Tamil")
 - tt ("Tatar")
 - te ("Telugu")
 - th ("Thai")
 - ti ("Tigrinya")
 - ts ("Tsonga")
 - tr ("Turkish")
 - tk ("Turkmen")
 - uk ("Ukrainian")
 - ur ("Urdu")
 - ug ("Uyghur")
 - uz ("Uzbek")
 - vi ("Vietnamese")
 - cy ("Welsh")
 - fy ("Western Frisian")
 - xh ("Xhosa")
 - yi ("Yiddish")
 - yo ("Yoruba")
 - zu ("Zulu")

If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!
Could not retrieve transcript for video ID BlqCg6ktwKI:
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=BlqCg6ktwKI! This is most likely caused by:

No transcripts were found for any of the requested language codes: ['en']

For this video (BlqCg6ktwKI) transcripts are available in the following languages:

(MANUALLY CREATED)
 - en-IN ("English (India)")[TRANSLATABLE]

(GENERATED)
 - hi ("Hindi (auto-generated)")[TRANSLATABLE]

(TRANSLATION LANGUAGES)
 - af ("Afrikaans")
 - ak ("Akan")
 - sq ("Albanian")
 - am ("Amharic")
 - ar ("Arabic")
 - hy ("Armenian")
 - as ("Assamese")
 - ay ("Aymara")
 - az ("Azerbaijani")
 - bn ("Bangla")
 - eu ("Basque")
 - be ("Belarusian")
 - bho ("Bhojpuri")
 - bs ("Bosnian")
 - bg ("Bulgarian")
 - my ("Burmese")
 - ca ("Catalan")
 - ceb ("Cebuano")
 - zh-Hans ("Chinese (Simplified)")
 - zh-Hant ("Chinese (Traditional)")
 - co ("Corsican")
 - hr ("Croatian")
 - cs ("Czech")
 - da ("Danish")
 - dv ("Divehi")
 - nl ("Dutch")
 - en ("English")
 - eo ("Esperanto")
 - et ("Estonian")
 - ee ("Ewe")
 - fil ("Filipino")
 - fi ("Finnish")
 - fr ("French")
 - gl ("Galician")
 - lg ("Ganda")
 - ka ("Georgian")
 - de ("German")
 - el ("Greek")
 - gn ("Guarani")
 - gu ("Gujarati")
 - ht ("Haitian Creole")
 - ha ("Hausa")
 - haw ("Hawaiian")
 - iw ("Hebrew")
 - hi ("Hindi")
 - hmn ("Hmong")
 - hu ("Hungarian")
 - is ("Icelandic")
 - ig ("Igbo")
 - id ("Indonesian")
 - ga ("Irish")
 - it ("Italian")
 - ja ("Japanese")
 - jv ("Javanese")
 - kn ("Kannada")
 - kk ("Kazakh")
 - km ("Khmer")
 - rw ("Kinyarwanda")
 - ko ("Korean")
 - kri ("Krio")
 - ku ("Kurdish")
 - ky ("Kyrgyz")
 - lo ("Lao")
 - la ("Latin")
 - lv ("Latvian")
 - ln ("Lingala")
 - lt ("Lithuanian")
 - lb ("Luxembourgish")
 - mk ("Macedonian")
 - mg ("Malagasy")
 - ms ("Malay")
 - ml ("Malayalam")
 - mt ("Maltese")
 - mi ("Māori")
 - mr ("Marathi")
 - mn ("Mongolian")
 - ne ("Nepali")
 - nso ("Northern Sotho")
 - no ("Norwegian")
 - ny ("Nyanja")
 - or ("Odia")
 - om ("Oromo")
 - ps ("Pashto")
 - fa ("Persian")
 - pl ("Polish")
 - pt ("Portuguese")
 - pa ("Punjabi")
 - qu ("Quechua")
 - ro ("Romanian")
 - ru ("Russian")
 - sm ("Samoan")
 - sa ("Sanskrit")
 - gd ("Scottish Gaelic")
 - sr ("Serbian")
 - sn ("Shona")
 - sd ("Sindhi")
 - si ("Sinhala")
 - sk ("Slovak")
 - sl ("Slovenian")
 - so ("Somali")
 - st ("Southern Sotho")
 - es ("Spanish")
 - su ("Sundanese")
 - sw ("Swahili")
 - sv ("Swedish")
 - tg ("Tajik")
 - ta ("Tamil")
 - tt ("Tatar")
 - te ("Telugu")
 - th ("Thai")
 - ti ("Tigrinya")
 - ts ("Tsonga")
 - tr ("Turkish")
 - tk ("Turkmen")
 - uk ("Ukrainian")
 - ur ("Urdu")
 - ug ("Uyghur")
 - uz ("Uzbek")
 - vi ("Vietnamese")
 - cy ("Welsh")
 - fy ("Western Frisian")
 - xh ("Xhosa")
 - yi ("Yiddish")
 - yo ("Yoruba")
 - zu ("Zulu")


### Open the file in read mode

In [ ]:
import json

with open('youtube_video_data_with_transcripts.json', 'r') as f:
    video_data = json.load(f)

In [ ]:
positive_data=video_data["positive"]
negative_data=video_data["negative"]
neutral_data=video_data["neutral"]

In [ ]:
import pandas as pd

positive_df=pd.DataFrame(positive_data)
negative_df=pd.DataFrame(negative_data)
neutral_df=pd.DataFrame(neutral_data)

In [ ]:
positive_df

,title,description,videoId,transcript
0,FOCUS ON YOURSELF NOT OTHERS (motivational video),Grab the power of words. Visit our store: http...,eBSeCp__xhI,"Today, I need you to embrace what comes hard t..."
1,DON&#39;T WASTE YOUR LIFE - Powerful Motivatio...,Don't Waste Your LIFE! So many take life for g...,-ESQmzDbnL8,Life How beautiful it is How amazing it is To ...
2,KILL YOUR EXCUSES - Motivational Speech,https://benlionelscott.com/subscribe Download ...,JjvN_hYDp3g,What gets you out of bed?\nWhat gets you off t...
3,One of the Greatest Speeches Ever | Steve Jobs,Steve Jobs: The Exclusive Biography - https://...,Tuw8hxrFBH8,today I want to tell you three stories from my...
4,CONFIDENCE - Motivational Speech,"Confidence. Spoken by Matt Damon, Les Brown, S...",Xu1kbRUCRic,The single\nmost determining factor of the qua...
...,...,...,...,...
190,Former Detroit gang leader uses second chance ...,A former Detroit gang leader who spent more th...,Ey5YOe0hsHk,I’LL BREAK DOWN WHAT’S GOING ON\nWHERE YOU LIV...
191,The Republicans need to focus on a positive me...,"On Friday's 'American Agenda', Special Assista...",Ko2GCavRe2w,E PARENTS DON'T GO ANYWHERE. NO CRICKET ESTABL...
192,God&#39;s Positive Message: Transforming Lives...,God's Positive Message: Transforming Lives wit...,5GfeGlBfLa4,can you give Jesus just 30 second right now if...
193,A Pep Talk from Kid President to You,We all need a little encouragement every now a...,l-gQLqv9f4o,I think we all need a pep\ntalk. (music playin...
194,"&#39;Roanoke is resilient&#39;, Mayor Lea send...","""Roanoke is resilient"" was the message from Ma...",3iDNvHv_sHY,in one place comes at a steep cost 3.5 billion...

### Labeling the videos

In [ ]:
positive_df['sentiment']=1
negative_df['sentiment']=-1
negative_df['sentiment']=0

### checking vidoes without subscript

In [ ]:
print(positive_df.transcript.isna().sum())
print(negative_df.transcript.isna().sum())
print(negative_df.transcript.isna().sum())

11
10
10

In [ ]:
positive_df=positive_df.dropna()
negative_df=negative_df.dropna()
neutral_df=neutral_df.dropna()

In [ ]:
print(positive_df.transcript.isna().sum())
print(negative_df.transcript.isna().sum())
print(negative_df.transcript.isna().sum())

0
0
0

In [ ]:
negative_df

,title,description,videoId,transcript,sentiment
0,Trump Losing again? 45’s nightmare comes true ...,Former President Obama and former first lady O...,Ao0bmNrRWhw,STARTS NOW. >> WE ARE REPORTING ON BE A RAM OB...,0
1,The System that Fuels Media Negativity,Get four bonus months when purchasing a two ye...,89FoKRtpAy4,The end… might not be near. Doom… might not be...,0
2,Are Republican voters having doubts about Vanc...,CNN senior data reporter Harry Enten breaks do...,3SD9swv7HZA,>>S RUNNW THAT HARRIS IS NOW AT TOP OF THE DO...,0
3,TRUMP FAIL: JD Vance 1st VP with negative favo...,Get your copy of “Aim for the Uprights” at htt...,-s0fXBQXSsA,Speaker 1: If you go back 44 years to 1980. ...,0
4,WATCH: Trump rally FULL SPEECH at St Cloud cam...,"Former president Donald Trump, as well as his ...",-4Drs2TmEhc,listen in. I don't know. Tom you better bring ...,0
...,...,...,...,...,...
195,Many children who survive gun violence face ba...,Firearm-related injuries among children have b...,KHPSd9LpYgQ,D INJURIES ARE ON THE RISE. ACCORDING TO THE L...,0
196,"As Texas students protest gun violence, here&#...","Students in North Texas, Uvalde and other citi...",RGmsJ3ITUtc,Across North Texas and across the country. Stu...,0
197,Patterns of Gun Violence in the United States,Annual Reviews is a non-profit publisher that ...,coUJ-TiR2qU,Mass casualty shootings in public places\nhave...,0
198,Gun violence in Chicago,As President Obama issues an executive order t...,_qvLQPu1fRg,CITY. ROSA FLORES HAS MORE. >> Reporter: BEFOR...,0
199,Texas lawmaker outlines legislation needed to ...,Democratic Texas state Sen. Roland Gutierrez r...,473uLFus5EQ,"HORRIBLE, HORRIBLE STORIES. MORGAN CHESKY, THA...",0

## Concating all three Dataframe into a single Dataframe

In [ ]:
df =pd.concat([positive_df,negative_df,neutral_df])
df

,title,description,videoId,transcript,sentiment
0,FOCUS ON YOURSELF NOT OTHERS (motivational video),Grab the power of words. Visit our store: http...,eBSeCp__xhI,"Today, I need you to embrace what comes hard t...",1.0
1,DON&#39;T WASTE YOUR LIFE - Powerful Motivatio...,Don't Waste Your LIFE! So many take life for g...,-ESQmzDbnL8,Life How beautiful it is How amazing it is To ...,1.0
2,KILL YOUR EXCUSES - Motivational Speech,https://benlionelscott.com/subscribe Download ...,JjvN_hYDp3g,What gets you out of bed?\nWhat gets you off t...,1.0
3,One of the Greatest Speeches Ever | Steve Jobs,Steve Jobs: The Exclusive Biography - https://...,Tuw8hxrFBH8,today I want to tell you three stories from my...,1.0
4,CONFIDENCE - Motivational Speech,"Confidence. Spoken by Matt Damon, Les Brown, S...",Xu1kbRUCRic,The single\nmost determining factor of the qua...,1.0
...,...,...,...,...,...
145,Informational Video!,,589NmYWyiZ4,"Okay, hello. Um, this is a bit weird, I know, ...",NaN
146,Non-Profit Owned MHC – Awardee Informational V...,PowerPoint presentation for Non-Profit Owned M...,0UTv0-wQlxY,"Good afternoon, everyone. My name is Mackenzie...",NaN
147,Toronto Local Appeal Body Informational Video,"In 2017, City Council passed Toronto Municipal...",P3KV89cJgJY,the Toronto local appeal body also known as T ...,NaN
148,Health Sciences Academy Informational Video,Students of the Health Sciences Academy at Wil...,-ba_Ylnn2i0,(music) Being in the Health Science Academy is...,NaN
149,PRMS Chromebook Case Informational Video,Outro Music by Approaching Nirvana http://yout...,vWNFoVNNCAI,Keeping your lent Chromebook safe is a\ntop pr...,NaN

## Removing Unnessasary columns

In [ ]:
df.drop(columns=['videoId'],inplace=True)

In [ ]:
df.columns

Index(['title', 'description', 'transcript', 'sentiment'], dtype='object')

In [ ]:
df.to_csv('youtube_data.csv', index=False)

## Reading the labeled Data

In [ ]:
import pandas as pd

df= pd.read_csv('youtube_data.csv')

In [ ]:
df

,title,description,transcript,sentiment
0,FOCUS ON YOURSELF NOT OTHERS (motivational video),Grab the power of words. Visit our store: http...,"Today, I need you to embrace what comes hard t...",1.0
1,DON&#39;T WASTE YOUR LIFE - Powerful Motivatio...,Don't Waste Your LIFE! So many take life for g...,Life How beautiful it is How amazing it is To ...,1.0
2,KILL YOUR EXCUSES - Motivational Speech,https://benlionelscott.com/subscribe Download ...,What gets you out of bed?\nWhat gets you off t...,1.0
3,One of the Greatest Speeches Ever | Steve Jobs,Steve Jobs: The Exclusive Biography - https://...,today I want to tell you three stories from my...,1.0
4,CONFIDENCE - Motivational Speech,"Confidence. Spoken by Matt Damon, Les Brown, S...",The single\nmost determining factor of the qua...,1.0
...,...,...,...,...
512,Informational Video!,NaN,"Okay, hello. Um, this is a bit weird, I know, ...",NaN
513,Non-Profit Owned MHC – Awardee Informational V...,PowerPoint presentation for Non-Profit Owned M...,"Good afternoon, everyone. My name is Mackenzie...",NaN
514,Toronto Local Appeal Body Informational Video,"In 2017, City Council passed Toronto Municipal...",the Toronto local appeal body also known as T ...,NaN
515,Health Sciences Academy Informational Video,Students of the Health Sciences Academy at Wil...,(music) Being in the Health Science Academy is...,NaN
516,PRMS Chromebook Case Informational Video,Outro Music by Approaching Nirvana http://yout...,Keeping your lent Chromebook safe is a\ntop pr...,NaN

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.isna().sum()

title          0
description    0
transcript     0
sentiment      0
dtype: int64

In [ ]:
df

,title,description,transcript,sentiment
0,FOCUS ON YOURSELF NOT OTHERS (motivational video),Grab the power of words. Visit our store: http...,"Today, I need you to embrace what comes hard t...",1.0
1,DON&#39;T WASTE YOUR LIFE - Powerful Motivatio...,Don't Waste Your LIFE! So many take life for g...,Life How beautiful it is How amazing it is To ...,1.0
2,KILL YOUR EXCUSES - Motivational Speech,https://benlionelscott.com/subscribe Download ...,What gets you out of bed?\nWhat gets you off t...,1.0
3,One of the Greatest Speeches Ever | Steve Jobs,Steve Jobs: The Exclusive Biography - https://...,today I want to tell you three stories from my...,1.0
4,CONFIDENCE - Motivational Speech,"Confidence. Spoken by Matt Damon, Les Brown, S...",The single\nmost determining factor of the qua...,1.0
...,...,...,...,...
369,Many children who survive gun violence face ba...,Firearm-related injuries among children have b...,D INJURIES ARE ON THE RISE. ACCORDING TO THE L...,0.0
370,"As Texas students protest gun violence, here&#...","Students in North Texas, Uvalde and other citi...",Across North Texas and across the country. Stu...,0.0
371,Patterns of Gun Violence in the United States,Annual Reviews is a non-profit publisher that ...,Mass casualty shootings in public places\nhave...,0.0
372,Gun violence in Chicago,As President Obama issues an executive order t...,CITY. ROSA FLORES HAS MORE. >> Reporter: BEFOR...,0.0
373,Texas lawmaker outlines legislation needed to ...,Democratic Texas state Sen. Roland Gutierrez r...,"HORRIBLE, HORRIBLE STORIES. MORGAN CHESKY, THA...",0.0

In [ ]:
df.to_csv('youtube_data.csv', index=False)

## Final Data

In [ ]:
df= pd.read_csv('youtube_data.csv')
df

,title,description,transcript,sentiment
0,focus on yourself not others motivational video,grab the power of words visit our store focus ...,today i need you to embrace what comes hard to...,1.0
1,dont waste your life powerful motivational spe...,dont waste your life so many take life for gra...,life how beautiful it is how amazing it is to ...,1.0
2,kill your excuses motivational speech,download this video and audio version by,what gets you out of bedwhat gets you off the ...,1.0
3,one of the greatest speeches ever steve jobs,steve jobs the exclusive biography steve jobs ...,today i want to tell you three stories from my...,1.0
4,confidence motivational speech,confidence spoken by matt damon les brown stev...,the singlemost determining factor of the quali...,1.0
...,...,...,...,...
363,many children who survive gun violence face ba...,firearmrelated injuries among children have be...,d injuries are on the rise according to the la...,0.0
364,as texas students protest gun violence heres w...,students in north texas uvalde and other citie...,across north texas and across the country stud...,0.0
365,patterns of gun violence in the united states,annual reviews is a nonprofit publisher that o...,mass casualty shootings in public placeshave o...,0.0
366,gun violence in chicago,as president obama issues an executive order t...,city rosa flores has more reporter before pres...,0.0
367,texas lawmaker outlines legislation needed to ...,democratic texas state sen roland gutierrez re...,horrible horrible stories morgan chesky thank ...,0.0

In [ ]:
df=df.dropna()

In [ ]:
df.isna().sum()

title          0
description    0
transcript     0
sentiment      0
dtype: int64

## Doing all the nessesary preprocessing

In [ ]:
import re
import string
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
nltk.download('stopwords')
nltk.download('wordnet')

lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

def filter_text(text):
  if isinstance(text, str): # Check if the text is a string
    text = text.lower() # Convert to lowercase

    # Removing punctuation
    extra_chars = string.punctuation + '\t\n'
    text= text.translate(str.maketrans('', '', extra_chars))

    # Removing extra spaces
    text = re.sub(r'\s+', ' ', text)

    # Remove HTML tags
    text = re.sub(r'<.*?>', '', text)

    # Remove URLs
    text = re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE)

    # Remove special characters and numbers
    text = re.sub(r'\[.*?\]', '', text)
    text = re.sub(r'\W', ' ', text)
    text = re.sub(r'\d', '', text)
    text = re.sub(r'\s+', ' ', text).strip()

    tokens = text.split()
    tokens = [lemmatizer.lemmatize(word) for word in tokens if word not in stop_words]

    return ' '.join(tokens)
  else:
      print(f"Non-string value encountered: {text}")
      return "" # Return an empty string if text is not a string

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

In [ ]:
df['title'] = df['title'].apply(filter_text)

<ipython-input-16-9915c90aad7b>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['title'] = df['title'].apply(filter_text)

In [ ]:
df['description'] = df['description'].apply(filter_text)

<ipython-input-17-aa3b1b2c4ebb>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['description'] = df['description'].apply(filter_text)

In [ ]:
df['transcript'] = df['transcript'].apply(filter_text)

<ipython-input-18-845996204667>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['transcript'] = df['transcript'].apply(filter_text)

In [ ]:
df

,title,description,transcript,sentiment
0,focus others motivational video,grab power word visit store focus others motiv...,today need embrace come hard day need accept c...,1.0
1,dont waste life powerful motivational speech v...,dont waste life many take life granted instead...,life beautiful amazing able rise morning sun s...,1.0
2,kill excuse motivational speech,download video audio version,get bedwhat get couch get gymits alarm parents...,1.0
3,one greatest speech ever steve job,steve job exclusive biography steve job delive...,today want tell three story life thats big dea...,1.0
4,confidence motivational speech,confidence spoken matt damon le brown steve ha...,singlemost determining factor quality lifeis p...,1.0
...,...,...,...,...
363,many child survive gun violence face barrier m...,firearmrelated injury among child rise nearly ...,injury rise according latest data nearly every...,0.0
364,texas student protest gun violence here whats ...,student north texas uvalde city across u stage...,across north texas across country student walk...,0.0
365,pattern gun violence united state,annual review nonprofit publisher offer accura...,mass casualty shooting public placeshave occur...,0.0
366,gun violence chicago,president obama issue executive order curb gun...,city rosa flores reporter president obama star...,0.0
367,texas lawmaker outline legislation needed redu...,democratic texas state sen roland gutierrez re...,horrible horrible story morgan chesky thank mu...,0.0

## Checking some transcripts

In [ ]:
check_trancripts= df['transcript']
check_trancripts[0]

'today need embrace come hard day need accept challenge today need fall love process plenty opportunity get discouraged lose passion think meant youre going reach destiny madeup mind give first time fifth time th time really mean didnt want bad enough something youre believing relentless moved impossible look youre discouraged long taking dont give people told youre attitude believe whole life going stop believing going take answer im going settle mediocrity im going keep pursuing put heart ask ourself really want really want write writing cause thinking thinking creates image get image get image growing building vision mind visionary thats changed world think keep competitive edge keep top ability think prepare mentally body limitation mind focus much go neck forget start everything start youre mentally ready youre never really physically prepared thats preparation start would life like look toward future decided im going allow fear stop im saying whatever gotta dont life gonna whoop surrender youre young make mistake dont let em eat cause everybody done made done made em got fail order win hey look man understand hit game shot got miss game shot know got tough road success always construction never clear path success people become successful people relentless attitude got hang bad break cause bad break comin usually come right big break happen get series bad break stumble lot people life success say anyone stumble fall get back'

## Conversion to csv

In [ ]:
df.to_csv('youtube_data.csv', index=False)

## Importing final CSV

In [ ]:
import pandas as pd

df= pd.read_csv('youtube_data.csv')
df

,title,description,transcript,sentiment
0,focus others motivational video,grab power word visit store focus others motiv...,today need embrace come hard day need accept c...,1.0
1,dont waste life powerful motivational speech v...,dont waste life many take life granted instead...,life beautiful amazing able rise morning sun s...,1.0
2,kill excuse motivational speech,download video audio version,get bedwhat get couch get gymits alarm parents...,1.0
3,one greatest speech ever steve job,steve job exclusive biography steve job delive...,today want tell three story life thats big dea...,1.0
4,confidence motivational speech,confidence spoken matt damon le brown steve ha...,singlemost determining factor quality lifeis p...,1.0
...,...,...,...,...
360,many child survive gun violence face barrier m...,firearmrelated injury among child rise nearly ...,injury rise according latest data nearly every...,0.0
361,texas student protest gun violence here whats ...,student north texas uvalde city across u stage...,across north texas across country student walk...,0.0
362,pattern gun violence united state,annual review nonprofit publisher offer accura...,mass casualty shooting public placeshave occur...,0.0
363,gun violence chicago,president obama issue executive order curb gun...,city rosa flores reporter president obama star...,0.0
364,texas lawmaker outline legislation needed redu...,democratic texas state sen roland gutierrez re...,horrible horrible story morgan chesky thank mu...,0.0

In [ ]:
helper_description=df['description']
helper_description[5]

'u navy admiral william h mcraven one decorated u commander delivers one best motivational'

## Combining the title, description and transcript into a single column

In [ ]:
df['combined_text']= df['title'] + ' ' + df['description'] + ' ' + df['transcript']

In [ ]:
df.drop(columns=['title','description','transcript'],inplace=True)
df

     sentiment                                      combined_text
0          1.0  focus others motivational video grab power wor...
1          1.0  dont waste life powerful motivational speech v...
2          1.0  kill excuse motivational speech download video...
3          1.0  one greatest speech ever steve job steve job e...
4          1.0  confidence motivational speech confidence spok...
..         ...                                                ...
360        0.0  many child survive gun violence face barrier m...
361        0.0  texas student protest gun violence here whats ...
362        0.0  pattern gun violence united state annual revie...
363        0.0  gun violence chicago president obama issue exe...
364        0.0  texas lawmaker outline legislation needed redu...

[365 rows x 2 columns]

In [ ]:
df['combined_text'][0]

'focus others motivational video grab power word visit store focus others motivational video today need embrace come hard day need accept challenge today need fall love process plenty opportunity get discouraged lose passion think meant youre going reach destiny madeup mind give first time fifth time th time really mean didnt want bad enough something youre believing relentless moved impossible look youre discouraged long taking dont give people told youre attitude believe whole life going stop believing going take answer im going settle mediocrity im going keep pursuing put heart ask ourself really want really want write writing cause thinking thinking creates image get image get image growing building vision mind visionary thats changed world think keep competitive edge keep top ability think prepare mentally body limitation mind focus much go neck forget start everything start youre mentally ready youre never really physically prepared thats preparation start would life like look toward future decided im going allow fear stop im saying whatever gotta dont life gonna whoop surrender youre young make mistake dont let em eat cause everybody done made done made em got fail order win hey look man understand hit game shot got miss game shot know got tough road success always construction never clear path success people become successful people relentless attitude got hang bad break cause bad break comin usually come right big break happen get series bad break stumble lot people life success say anyone stumble fall get back'

In [ ]:
df.to_csv('combined_youtube_data.csv', index=False)

## Reading combined csv

In [51]:
import pandas as pd

df= pd.read_csv('combined_youtube_data.csv')
df

     sentiment                                      combined_text
0          1.0  focus others motivational video grab power wor...
1          1.0  dont waste life powerful motivational speech v...
2          1.0  kill excuse motivational speech download video...
3          1.0  one greatest speech ever steve job steve job e...
4          1.0  confidence motivational speech confidence spok...
..         ...                                                ...
360        0.0  many child survive gun violence face barrier m...
361        0.0  texas student protest gun violence here whats ...
362        0.0  pattern gun violence united state annual revie...
363        0.0  gun violence chicago president obama issue exe...
364        0.0  texas lawmaker outline legislation needed redu...

[365 rows x 2 columns]

In [52]:
# Map the labels
def map_labels(label):
    if label == -1:
        return 0  # Map -1 to 0
    elif label == 0:
        return 1  # Map 0 to 1
    elif label == 1:
        return 2  # Map 1 to 2

df['sentiment'] = df['sentiment'].apply(map_labels)

In [54]:
df

     sentiment                                      combined_text
0            2  focus others motivational video grab power wor...
1            2  dont waste life powerful motivational speech v...
2            2  kill excuse motivational speech download video...
3            2  one greatest speech ever steve job steve job e...
4            2  confidence motivational speech confidence spok...
..         ...                                                ...
360          1  many child survive gun violence face barrier m...
361          1  texas student protest gun violence here whats ...
362          1  pattern gun violence united state annual revie...
363          1  gun violence chicago president obama issue exe...
364          1  texas lawmaker outline legislation needed redu...

[365 rows x 2 columns]

## Model training

In [55]:
from transformers import BertTokenizer, BertForSequenceClassification
import torch

checkpoint='bert-large-uncased'
tokenizer= BertTokenizer.from_pretrained(checkpoint)
model= BertForSequenceClassification.from_pretrained(checkpoint, num_labels=3)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-large-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

## Tokenize function

In [56]:
def tokenize_data(data):
  return tokenizer(data['combined_text'], truncation=True)

## Tokenize dataset

In [57]:
tokenize_data = df.apply(tokenize_data, axis=1)

In [58]:
sentiment=df['sentiment']

In [59]:
tokenize_data[0]

{'input_ids': [101, 3579, 2500, 14354, 2389, 2678, 6723, 2373, 2773, 3942, 3573, 3579, 2500, 14354, 2389, 2678, 2651, 2342, 9979, 2272, 2524, 2154, 2342, 5138, 4119, 2651, 2342, 2991, 2293, 2832, 7564, 4495, 2131, 22585, 4558, 6896, 2228, 3214, 2115, 2063, 2183, 3362, 10461, 2081, 6279, 2568, 2507, 2034, 2051, 3587, 2051, 16215, 2051, 2428, 2812, 2134, 2102, 2215, 2919, 2438, 2242, 2115, 2063, 8929, 21660, 2333, 5263, 2298, 2115, 2063, 22585, 2146, 2635, 2123, 2102, 2507, 2111, 2409, 2115, 2063, 7729, 2903, 2878, 2166, 2183, 2644, 8929, 2183, 2202, 3437, 10047, 2183, 7392, 19960, 3695, 26775, 3012, 10047, 2183, 2562, 11828, 2404, 2540, 3198, 14635, 2884, 2546, 2428, 2215, 2428, 2215, 4339, 3015, 3426, 3241, 3241, 9005, 3746, 2131, 3746, 2131, 3746, 3652, 2311, 4432, 2568, 28036, 2008, 2015, 2904, 2088, 2228, 2562, 6975, 3341, 2562, 2327, 3754, 2228, 7374, 10597, 2303, 22718, 2568, 3579, 2172, 2175, 3300, 5293, 2707, 2673, 2707, 2115, 2063, 10597, 3201, 2115, 2063, 2196, 2428, 8186, 4810, 2008, 2015, 7547, 2707, 2052, 2166, 2066, 2298, 2646, 2925, 2787, 10047, 2183, 3499, 3571, 2644, 10047, 3038, 3649, 10657, 2123, 2102, 2166, 6069, 2040, 7361, 7806, 2115, 2063, 2402, 2191, 6707, 2123, 2102, 2292, 7861, 4521, 3426, 7955, 2589, 2081, 2589, 2081, 7861, 2288, 8246, 2344, 2663, 4931, 2298, 2158, 3305, 2718, 2208, 2915, 2288, 3335, 2208, 2915, 2113, 2288, 7823, 2346, 3112, 2467, 2810, 2196, 3154, 4130, 3112, 2111, 2468, 3144, 2111, 21660, 7729, 2288, 6865, 2919, 3338, 3426, 2919, 3338, 4012, 2378, 2788, 2272, 2157, 2502, 3338, 4148, 2131, 2186, 2919, 3338, 21811, 2843, 2111, 2166, 3112, 2360, 3087, 21811, 2991, 2131, 2067, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [7]:
input_ids = [item['input_ids'] for item in tokenize_data]
attention_masks = [item['attention_mask'] for item in tokenize_data]

In [60]:
tokenized_df = pd.DataFrame({
    'input_ids': input_ids,
    'attention_mask': attention_masks,
    'labels': df['sentiment']
})

In [61]:
tokenized_df

,input_ids,attention_mask,labels
0,"[101, 3579, 2500, 14354, 2389, 2678, 6723, 237...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",2
1,"[101, 2123, 2102, 5949, 2166, 3928, 14354, 238...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",2
2,"[101, 3102, 8016, 14354, 2389, 4613, 8816, 267...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",2
3,"[101, 2028, 4602, 4613, 2412, 3889, 3105, 3889...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",2
4,"[101, 7023, 14354, 2389, 4613, 7023, 5287, 471...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",2
...,...,...,...
360,"[101, 2116, 2775, 5788, 3282, 4808, 2227, 8803...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",1
361,"[101, 3146, 3076, 6186, 3282, 4808, 2182, 2054...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",1
362,"[101, 5418, 3282, 4808, 2142, 2110, 3296, 3319...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",1
363,"[101, 3282, 4808, 3190, 2343, 8112, 3277, 3237...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",1
364,"[101, 3146, 2375, 8571, 12685, 6094, 2734, 554...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",1

## Dynamic Padding

In [62]:
from transformers import DataCollatorWithPadding

data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

## Spliting into train and validation data

In [63]:
from sklearn.model_selection import train_test_split

train_data, val_data= train_test_split(tokenized_df, test_size=0.2, random_state=42)
train_data = train_data.reset_index(drop=True)
val_data = val_data.reset_index(drop=True)

In [64]:
train_data

,input_ids,attention_mask,labels
0,"[101, 23634, 2099, 3077, 2158, 2202, 2166, 377...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",1
1,"[101, 6396, 17299, 2951, 2265, 4803, 3282, 480...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",1
2,"[101, 6366, 4997, 2739, 3720, 4955, 4274, 2193...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",1
3,"[101, 2659, 2482, 2497, 3112, 2466, 7150, 2278...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",2
4,"[101, 7872, 3526, 3112, 2466, 2424, 3949, 4248...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",2
...,...,...,...
287,"[101, 3958, 2659, 2482, 2497, 3112, 2466, 3958...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",2
288,"[101, 10576, 10911, 2643, 2360, 10710, 2100, 3...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",2
289,"[101, 4339, 4187, 3906, 3319, 2442, 3582, 3357...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",1
290,"[101, 3282, 4808, 2448, 25883, 2637, 2182, 425...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",1
291,"[101, 2166, 2460, 2444, 2296, 2154, 2643, 5006...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",2

In [65]:
val_data

,input_ids,attention_mask,labels
0,"[101, 2444, 5925, 2739, 2444, 5958, 2251, 4942...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",1
1,"[101, 2990, 5003, 2166, 6040, 2689, 2166, 2442...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",2
2,"[101, 7939, 12638, 2899, 4613, 2681, 25146, 20...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",2
3,"[101, 4187, 3319, 2137, 8582, 2113, 5409, 3604...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",1
4,"[101, 3112, 2466, 10210, 5831, 3410, 10210, 58...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",2
...,...,...,...
68,"[101, 3422, 7226, 2368, 8847, 5604, 4997, 2522...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",1
69,"[101, 1056, 2213, 3112, 2466, 21877, 2140, 790...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",2
70,"[101, 5902, 11338, 22401, 2078, 7053, 4378, 25...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",2
71,"[101, 4997, 4471, 2919, 2739, 18560, 3602, 301...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",1
72,"[101, 4254, 3282, 4808, 12084, 2637, 17870, 10...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",1

In [15]:
# !pip install datasets

Collecting datasets
  Downloading datasets-2.20.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from datasets) (3.15.4)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from datasets) (1.26.4)
Collecting pyarrow>=15.0.0 (from datasets)
  Downloading pyarrow-17.0.0-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (3.3 kB)
Requirement already satisfied: pyarrow-hotfix in /usr/local/lib/python3.10/dist-packages (from datasets) (0.6)
Collecting dill<0.3.9,>=0.3.0 (from datasets)
  Downloading dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from datasets) (2.1.4)
Collecting requests>=2.32.2 (from datasets)
  Downloading requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.10/dist-packages (from datasets) (4.66.4)
Collecting xxhash (from datasets)
  Downloading xxhash-3.4.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting multiprocess (from datasets)
  Downloading multiprocess-0.70.16-py310-none-any.whl.metadata (7.2 kB)
Collecting fsspec<=2024.5.0,>=2023.1.0 (from fsspec[http]<=2024.5.0,>=2023.1.0->datasets)
  Downloading fsspec-2024.5.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from datasets) (3.9.5)
Requirement already satisfied: huggingface-hub>=0.21.2 in /usr/local/lib/python3.10/dist-packages (from datasets) (0.23.5)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from datasets) (24.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from datasets) (6.0.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.9.4)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (4.0.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.21.2->datasets) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.2->datasets) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.2->datasets) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.2->datasets) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.2->datasets) (2024.7.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2024.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.16.0)
Downloading datasets-2.20.0-py3-none-any.whl (547 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 547.8/547.8 kB 9.7 MB/s eta 0:00:00
Downloading dill-0.3.8-py3-none-any.whl (116 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 8.2 MB/s eta 0:00:00
Downloading fsspec-2024.5.0-py3-none-any.whl (316 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 316.1/316.1 kB 22.3 MB/s eta 0:00:00
Downloading pyarrow-17.0.0-cp310-cp310-manylinux_2_28_x86_64.whl (39.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.9/39.9 MB 21.2 MB/s eta 0:00:00
Downloading requests-2.32.3-py3-none-any.whl (64 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.9/64.9 kB 5.2 MB/s eta 0:00:00
Downloading multiprocess-0.70.16-py310-none-any.whl (134 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 11.3 MB/s eta 0:00:00
Downloading xxhash-3.4.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (194 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 14.7 MB/s eta 0:00:00
Installing collected packages: xxhash, requests, pyarrow, fsspec, dill, multiprocess, datasets
  Attempting uninstall: requests
    Found existing installation: requests 2.31.0
    Uninstalling requests-2.31.0:
      Successfully uninstalled requests-2.31.0
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 14.0.2
    Uninstalling pyarrow-14.0.2:
      Successfully uninstalled pyarrow-14.0.2
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2024.6.1
    Uninstalling fsspec-2024.6.1:
      Successfully uninstalled fsspec-2024.6.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torch 2.3.1+cu121 requires nvidia-cublas-cu12==12.1.3.1; platform_system == "Linux" and platform_machine == "x86_64", which is not installed.
torch 2.3.1+cu121 requires nvidia-cuda-cupti-cu12==12.1.105; platform_system == "Linux" and platform_machine == "x86_64", which is not installed.
torch 2.3.1+cu121 requires nvidia-cuda-nvrtc-cu12==12.1.105; platform_system == "Linux" and platform_machine == "x86_64", which is not installed.
torch 2.3.1+cu121 requires nvidia-cuda-runtime-cu12==12.1.105; platform_system == "Linux" and platform_machine == "x86_64", which is not installed.
torch 2.3.1+cu121 requires nvidia-cudnn-cu12==8.9.2.26; platform_system == "Linux" and platform_machine == "x86_64", which is not installed.
torch 2.3.1+cu121 requires nvidia-cufft-cu12==11.0.2.54; platform_system == "Linux" and platform_machine == "x86_64", which is not installed.
torch 2.3.1+cu121 requires nvidia-curand-cu12==10.3.2.106; platform_system == "Linux" and platform_machine == "x86_64", which is not installed.
torch 2.3.1+cu121 requires nvidia-cusolver-cu12==11.4.5.107; platform_system == "Linux" and platform_machine == "x86_64", which is not installed.
torch 2.3.1+cu121 requires nvidia-cusparse-cu12==12.1.0.106; platform_system == "Linux" and platform_machine == "x86_64", which is not installed.
torch 2.3.1+cu121 requires nvidia-nccl-cu12==2.20.5; platform_system == "Linux" and platform_machine == "x86_64", which is not installed.
torch 2.3.1+cu121 requires nvidia-nvtx-cu12==12.1.105; platform_system == "Linux" and platform_machine == "x86_64", which is not installed.
cudf-cu12 24.4.1 requires pyarrow<15.0.0a0,>=14.0.1, but you have pyarrow 17.0.0 which is incompatible.
gcsfs 2024.6.1 requires fsspec==2024.6.1, but you have fsspec 2024.5.0 which is incompatible.
google-colab 1.0.0 requires requests==2.31.0, but you have requests 2.32.3 which is incompatible.
ibis-framework 8.0.0 requires pyarrow<16,>=2, but you have pyarrow 17.0.0 which is incompatible.
Successfully installed datasets-2.20.0 dill-0.3.8 fsspec-2024.5.0 multiprocess-0.70.16 pyarrow-17.0.0 requests-2.32.3 xxhash-3.4.1

In [70]:
from datasets import Dataset

train_dataset = Dataset.from_pandas(train_data)
val_dataset = Dataset.from_pandas(val_data)

In [71]:
train_dataset.set_format('torch')
val_dataset.set_format('torch')

In [72]:
train_dataset, val_dataset

(Dataset({
     features: ['input_ids', 'attention_mask', 'labels'],
     num_rows: 292
 }),
 Dataset({
     features: ['input_ids', 'attention_mask', 'labels'],
     num_rows: 73
 }))

In [74]:
train_dataset['input_ids'][0]

tensor([  101, 23634,  2099,  3077,  2158,  2202,  2166,  3773,  1047,  4997,
         5703,  5211, 10439,  2095, 11614, 23634,  2099,  3077,  2158,  2441,
         6202, 10439,  3042,  3662,  2485,  2454,  7922,  2417,  2551,  2424,
         2592,  2028,  2574,  2131,  3288,  2047,  2095, 11614, 23634,  2099,
         3077,  2158,  2441,  4518,  6202, 10439,  3042,  3662,  2485,  2454,
         7922,  2417,  2574,  3656, 17710, 23549,  5462,  5920,  1059, 16206,
         2015,  4388,  3308,  2444, 19863, 11368,  2618,  3892,  5720,  2158,
         5816,  3305,  3599,  3047, 10240,  2092,  2204,  3944,  6517,  2466,
         2126,  2105,  3043,  2298,  2028,  2126,  2785,  2228,  2175,  8169,
        10439,  2718, 10439,  2156,  5703,  2156,  2115,  2063,  9361,  7494,
         4923,  4003,  5703,  2092,  2553,  2095, 11614,  2441,  5211, 10439,
         2387,  2485,  4997,  5356,  5703,  2941,  5310,  8278,  3277,  4074,
         2441, 10439,  2387,  5356,  5703,  4997,  2298,  3898,  2915,  4207,
         2941,  5976,  7922,  4070,  2995,  7494,  5816,  2520,  5503,  2360,
         2196,  2941,  2439,  2769,  2036,  2360,  2095, 11614,  4074, 19649,
         2188, 23634,  2099,  3077,  2067,  2267,  2118,  8506,  2150,  4699,
        19920,  2155,  2360, 22817, 19920, 10439,  2170,  5863,  7415,  2211,
         2437,  3119,  8552,  5211,  2367,  5724,  9432, 26618,  2387,  4070,
         2155,  2360,  2165,  3898, 17643,  2497,  3241,  9868,  2155,  3361,
         2166,  2626,  5920,  3602,  2303,  2179,  2279,  2154,  6908,  2392,
         3345,  5503,  2147,  5446,  2215,  5863,  7415,  2191,  2469,  2111,
         3305,  2027,  2890,  2559,  2156,  5356,  5703, 10439,  2360,  4074,
         2941,  3139,  3891,  2801,  2113,  5515, 23131,  2478,  4132,  5724,
         6202,  4132,  2801,  2052,  2404,  4997,  5356,  5703,  5356,  7785,
         5356, 18691,  2342,  2644,  2342,  4964,  2215,  2155,  2215,  8278,
         4964,  2613,  4861,  2194, 28049,  7386,  4022,  7386,  3443, 11265,
        25394, 11461,  2190,  8909,  7475, 18555,  2518, 23009,  4207,  1057,
         3433,  2194,  3843,  7271,  2360, 14686,  1057,  5863,  7415,  6171,
         6517, 24589,  2963,  6659,  2739,  2584,  3745, 25805, 22717,  2155,
         3745,  2174,  6987,  4953,  4070,  4847,  9394, 18777,  3012, 23009,
         2170, 27141,  3433,  2194,  3613,  5157,  3437,  2194,  2444,   102])

## Dividing the data into batches using DataLoader

In [75]:
from torch.utils.data import DataLoader

train_dataloader = DataLoader(train_dataset, shuffle=True, batch_size=8, collate_fn=data_collator)
val_dataloader = DataLoader(train_dataset, batch_size=8, collate_fn=data_collator)

## Optimizer

In [76]:
from transformers import AdamW

optimizer = AdamW(model.parameters(), lr=3e-5)

/usr/local/lib/python3.10/dist-packages/transformers/optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(

## Initializing Accelerator

In [77]:
from accelerate import Accelerator

accelerator = Accelerator()

train_dl, eval_dl, model, optimizer = accelerator.prepare(
    train_dataloader, val_dataloader, model, optimizer
)

## Some initialization

In [81]:
num_epochs=3
num_training_steps= num_epochs * len(train_dataloader)
gradient_accumulation_steps = 1

## Scheduler and loss function

In [80]:
from transformers import get_scheduler


lr_scheduler= get_scheduler("linear",
                            optimizer=optimizer,
                            num_warmup_steps=0,
                            num_training_steps=num_training_steps
                            )
criterion = torch.nn.CrossEntropyLoss()

In [50]:
from tqdm.auto import tqdm

progress_bar = tqdm(range(num_training_steps))
criterion = torch.nn.CrossEntropyLoss()

  0%|          | 0/111 [00:00<?, ?it/s]

In [83]:
!pip install evaluate

Collecting evaluate
  Downloading evaluate-0.4.2-py3-none-any.whl.metadata (9.3 kB)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from evaluate) (2.20.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from evaluate) (1.26.4)
Requirement already satisfied: dill in /usr/local/lib/python3.10/dist-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from evaluate) (2.1.4)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.10/dist-packages (from evaluate) (2.32.3)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.10/dist-packages (from evaluate) (4.66.4)
Requirement already satisfied: xxhash in /usr/local/lib/python3.10/dist-packages (from evaluate) (3.4.1)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.10/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.10/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2024.5.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from evaluate) (0.23.5)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from evaluate) (24.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from datasets>=2.0.0->evaluate) (3.15.4)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.10/dist-packages (from datasets>=2.0.0->evaluate) (17.0.0)
Requirement already satisfied: pyarrow-hotfix in /usr/local/lib/python3.10/dist-packages (from datasets>=2.0.0->evaluate) (0.6)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from datasets>=2.0.0->evaluate) (3.9.5)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from datasets>=2.0.0->evaluate) (6.0.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->evaluate) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->evaluate) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->evaluate) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->evaluate) (2024.7.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->evaluate) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->evaluate) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas->evaluate) (2024.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.9.4)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (4.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.16.0)
Downloading evaluate-0.4.2-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 2.2 MB/s eta 0:00:00
Installing collected packages: evaluate
Successfully installed evaluate-0.4.2

In [ ]:
import evaluate

for epoch in range(num_epochs):

  total_loss = 0
  model.train()

  for batch in train_dl:
    input_ids = batch['input_ids']
    attention_mask = batch['attention_mask']
    labels = batch['labels']

    outputs = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
    loss= outputs.loss
    total_loss += loss.item()
    accelerator.backward(loss) #Compute the gradients by backpropagation.

    optimizer.step()
    lr_scheduler.step()
    optimizer.zero_grad()
    progress_bar.update(1)

    avg_train_loss = total_loss / len(train_dataloader)
    print(f"Epoch {epoch+1}/{num_epochs}, Training Loss: {avg_train_loss}")

  model.eval()
  accuracy_metric = evaluate.load("accuracy")
  f1_metric = evaluate.load("f1", average="weighted")
  total_val_loss = 0
  correct_predictions = 0
  total_predictions = 0

  for batch in eval_dl:
    input_ids = batch['input_ids']
    attention_mask = batch['attention_mask']
    labels = batch['labels']

    with torch.no_grad():
      outputs = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)

      loss = outputs.loss
      total_val_loss += loss.item()

      logits = outputs.logits
      predictions = torch.argmax(logits, dim=-1)

      accuracy_metric.add_batch(predictions=predictions, references=batch["labels"])
      f1_metric.add_batch(predictions=predictions, references=batch["labels"])
  accuracy_metric.compute()
  f1_metric.compute()

  avg_val_loss = total_val_loss / len(eval_dl)
  print(f"Validation Loss: {avg_val_loss}, Validation Accuracy: {accuracy['accuracy']}, Validation F1 Score: {f1['f1']}")